#!/bin/sh

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd ${SCRIPTPATH}/..

rm -f ./MPC_Config/generated/sctk_mpit.h

${SCRIPTPATH}/mpit/gen_mpit_vars.sh 1> ./MPC_Config/generated/sctk_mpit.h


if test -e "${PWD}/MPC_Config/generated/sctk_mpit.h"
then
	echo "Sucessfully generated MPI header" >&2
else
	echo "ERROR : Failed to generate sctk_mpit.h" >&2
	exit 1
fi
