#!/bin/sh
############################# MPC License ############################## 
# Wed Nov 19 15:19:19 CET 2008                                         # 
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
#                                                                      # 
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
# This file is part of the MPC Runtime.                                # 
#                                                                      # 
# This software is governed by the CeCILL-C license under French law   # 
# and abiding by the rules of distribution of free software.  You can  # 
# use, modify and/ or redistribute the software under the terms of     # 
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
# following URL http://www.cecill.info.                                # 
#                                                                      # 
# The fact that you are presently reading this means that you have     # 
# had knowledge of the CeCILL-C license and that you accept its        # 
# terms.                                                               # 
#                                                                      # 
# Authors:                                                             # 
#   - PERACHE Marc marc.perache@cea.fr                                 # 
#                                                                      # 
######################################################################## 
SOURCE_DIR="$1"
INCLUDE_DIR="$2"

mkdir -p ${INCLUDE_DIR}
if test "$?" != "0" ; then 
exit 1
fi

cd ${INCLUDE_DIR}
if test "$?" != "0" ; then 
exit 1
fi

for i in ${SOURCE_DIR}/*.h; do 
    if test -f $i ; then 
    NAME="`basename $i`"
    if test -f "${INCLUDE_DIR}/$NAME" ; then 
	echo "    $NAME already here"
	exit 1
    else
	echo "INC  $NAME"
	ln -s $i $NAME
	if test "$?" != "0" ; then 
	    exit 1
	fi
    fi
    fi
done
