#!/bin/sh
############################# MPC License ############################## 
# Wed Nov 19 15:19:19 CET 2008                                         # 
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
#                                                                      # 
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
# This file is part of the MPC Runtime.                                # 
#                                                                      # 
# This software is governed by the CeCILL-C license under French law   # 
# and abiding by the rules of distribution of free software.  You can  # 
# use, modify and/ or redistribute the software under the terms of     # 
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
# following URL http://www.cecill.info.                                # 
#                                                                      # 
# The fact that you are presently reading this means that you have     # 
# had knowledge of the CeCILL-C license and that you accept its        # 
# terms.                                                               # 
#                                                                      # 
# Authors:                                                             # 
#   - PERACHE Marc marc.perache@cea.fr                                 # 
#                                                                      # 
######################################################################## 

sctk_echo "Generating reconfigure script"

cat <<EOF > reconfigure
#!/bin/sh
EOF

#PATH="\$PATH:."
#export PATH

header_sh >> reconfigure

if test "$IN_CONFIG_STATUS" = "1" ; then 
printf "CONFIGURE_LINE=\"$CONFIGURE_LINE">> reconfigure
echo "\"" >> reconfigure
else
printf "CONFIGURE_LINE=\"$0 ">> reconfigure
for i in "$@" ; do 
printf " '$i'">> reconfigure
done
echo "\"" >> reconfigure
fi

export -p  >> reconfigure


cat <<EOF >> reconfigure
MPC_SOURCE_DIR="$MPC_SOURCE_DIR"
MODULE_LIST="$MODULE_LIST"
SCTK_CFLAGS="$SCTK_CFLAGS"
SCTK_LDFLAGS="$SCTK_LDFLAGS"
SCTK_PREFIX="$SCTK_PREFIX"
SCTK_EPREFIX="$SCTK_EPREFIX"
SCTK_BIN_DIR="$SCTK_BIN_DIR"
SCTK_LIB_DIR="$SCTK_LIB_DIR"
SCTK_MAN_DIR="$SCTK_MAN_DIR"
SCTK_SHARE_DIR="$SCTK_SHARE_DIR"
SCTK_INCLUDE_DIR="$SCTK_INCLUDE_DIR"
MPC_VERSION="$MPC_VERSION"
SCTK_FORTRAN="$SCTK_FORTRAN"

SCTK_CC="$SCTK_CC"
SCTK_GCC="$SCTK_GCC"
SCTK_F77="$SCTK_F77"
SCTK_CXX="$SCTK_CXX"
SCTK_AR="$SCTK_AR"
MPC_COMPILER_CFLAGS="$MPC_COMPILER_CFLAGS"
COMPILER_SPECIFC_FLAGS="$COMPILER_SPECIFC_FLAGS"
SCTK_ARCH_OPTIM="$SCTK_ARCH_OPTIM"
SCTK_FFLAGS="$SCTK_FFLAGS"
SCTK_MPC_USE_ZLIB="$SCTK_MPC_USE_ZLIB"

if test "\$SCTK_MPC_RECONFIGURE" = "1"; then 
echo "\$CONFIGURE_LINE \$@"
eval "\$CONFIGURE_LINE \$@"
RES=\$?
rm ./reconfigure.tmp
exit \$RES
else

cat <<EOFFILE > ./reconfigure.tmp
#!/bin/sh
SCTK_MPC_RECONFIGURE="1"
EOFFILE
cat \$0 >> ./reconfigure.tmp
chmod 755 ./reconfigure.tmp
exec ./reconfigure.tmp \$@
fi

#echo "\$CONFIGURE_LINE \$@"
#eval "\$CONFIGURE_LINE \$@"

EOF

chmod 755 reconfigure
