#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#                                                                      #
########################################################################

#get config file for the run if not already given
if test "$MPCRUN_CONFIG_FILE" = "" ; then
	echo processes for the run ?
	read MPCRUN_CONFIG_FILE
fi

verify if hydra is Intel version and not mpich
HYDRA_VERSION="`mpiexec.hydra --version`"
if test "\${HYDRA_VERSION#*'Intel'}" != "\$HYDRA_VERSION"; then
	LAUNCH_COMMAND="mpiexec.hydra"
	I=0
	J=0
	while read line; do 
		if test "${line}" != ""; then
			I=$(($I + 1)); 
		fi
	done < "${MPCRUN_CONFIG_FILE}"
	#create launch command for hydra
	while read line; do
		if test "${line}" != ""; then
			line=`echo ${line} | sed -e 's/-p/-n/'`
			if test "$J" = $(($I - 1)); then
				LAUNCH_COMMAND="${LAUNCH_COMMAND} ${line} $USER_ARGS $SCTK_ARGS"; 
			else
				LAUNCH_COMMAND="${LAUNCH_COMMAND} ${line} $USER_ARGS $SCTK_ARGS :"; 
			fi
			J=$(($J + 1)); 
		fi
	done < "${MPCRUN_CONFIG_FILE}"
	export I_MPI_MIC=enable
	echo "Launching command $LAUNCH_COMMAND"
else
	echo "You must use Intel hydra launcher for hybrid (host + MIC) runs"
	exit
fi




