/* ############################# MPC License ############################## */
/* # Wed Nov 19 15:19:19 CET 2008                                         # */
/* # Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # */
/* #                                                                      # */
/* # IDDN.FR.001.230040.000.S.P.2007.000.10000                            # */
/* # This file is part of the MPC Runtime.                                # */
/* #                                                                      # */
/* # This software is governed by the CeCILL-C license under French law   # */
/* # and abiding by the rules of distribution of free software.  You can  # */
/* # use, modify and/ or redistribute the software under the terms of     # */
/* # the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # */
/* # following URL http://www.cecill.info.                                # */
/* #                                                                      # */
/* # The fact that you are presently reading this means that you have     # */
/* # had knowledge of the CeCILL-C license and that you accept its        # */
/* # terms.                                                               # */
/* #                                                                      # */
/* # Authors:                                                             # */
/* #   - BESNARD Jean-Baptiste jean-baptiste.besnard@cea.fr               # */
/* #                                                                      # */
/* ######################################################################## */

/* Syntax : PROBE( UNIQUE_KEY, PARENT_KEY, "Short Desc")
 * use NO_PARENT if a given probe has no paren */

PROBE( MPI, NO_PARENT, MPI Interface calls )
	PROBE( MPI_POINT_TO_POINT, MPI, MPI point to point calls )
		PROBE( MPC_Iprobe, MPI_POINT_TO_POINT , MPC_Iprobe calls )
		PROBE( MPC_Probe, MPI_POINT_TO_POINT , MPC_Probe calls )
		PROBE( MPC_Irecv, MPI_POINT_TO_POINT,  MPC_Irecv calls )
		PROBE( MPC_Irecv_pack, MPI_POINT_TO_POINT,  MPC_Irecv_pack calls )
		PROBE( MPC_Irsend, MPI_POINT_TO_POINT,  MPC_Irsend calls )
		PROBE( MPC_Isend, MPI_POINT_TO_POINT,  MPC_Isend calls )
		PROBE( MPC_Isend_pack, MPI_POINT_TO_POINT,  MPC_Isend_pack calls )
		PROBE( MPC_Issend, MPI_POINT_TO_POINT,  MPC_Issend calls )
		PROBE( MPC_Recv, MPI_POINT_TO_POINT,  MPC_Recv calls )
		PROBE( MPC_Rsend, MPI_POINT_TO_POINT,  MPC_Rsend calls )
		PROBE( MPC_Send, MPI_POINT_TO_POINT,  MPC_Send calls )
		PROBE( MPC_Sendrecv, MPI_POINT_TO_POINT,  MPC_Sendrecv calls )
		PROBE( MPC_Ssend, MPI_POINT_TO_POINT,  MPC_Ssend calls )
		PROBE( MPC_Ibsend, MPI_POINT_TO_POINT,  MPC_Ibsend calls )
		PROBE( MPC_Test, MPI_POINT_TO_POINT,  MPC_Test calls )
		PROBE( MPC_Test_no_check, MPI_POINT_TO_POINT,  MPC_Test_no_check calls )
		PROBE( MPC_Test_check, MPI_POINT_TO_POINT,  MPC_Test_check calls )
		PROBE( MPC_Proceed, MPI_POINT_TO_POINT,  MPC_Proceed calls )
	PROBE( MPI_WAIT, MPI, MPI Waiting calls )
		PROBE( MPC_Wait, MPI_WAIT,  MPC_Wait calls )
		PROBE( MPC_Wait_pending, MPI_WAIT,  MPC_Wait_pending calls )
		PROBE( MPC_Wait_pending_all_comm, MPI_WAIT,  MPC_Wait_pending_all_comm calls )
		PROBE( MPC_Waitall, MPI_WAIT,  MPC_Waitall calls )
		PROBE( MPC_Waitany, MPI_WAIT,  MPC_Waitany calls )
		PROBE( MPC_Waitsome, MPI_WAIT,  MPC_Waitsome calls )
	PROBE( MPI_COLL, MPI, MPI collectives calls )
		PROBE( MPC_Allgather, MPI_COLL,  MPC_Allgather calls )
		PROBE( MPC_Allgatherv, MPI_COLL,  MPC_Allgatherv calls )
		PROBE( MPC_Allreduce, MPI_COLL,  MPC_Allreduce calls )
		PROBE( MPC_Alltoall, MPI_COLL,  MPC_Alltoall calls )
		PROBE( MPC_Alltoallv, MPI_COLL,  MPC_Alltoallv calls )
		PROBE( MPC_Barrier, MPI_COLL,  MPC_Barrier calls )
		PROBE( MPC_Bcast, MPI_COLL,  MPC_Bcast calls )
		PROBE( MPC_Bsend, MPI_COLL,  MPC_Bsend calls )
		PROBE( MPC_Gather, MPI_COLL,  MPC_Gather calls )
		PROBE( MPC_Gatherv, MPI_COLL,  MPC_Gatherv calls )
		PROBE( MPC_Reduce, MPI_COLL,  MPC_Reduce calls )
		PROBE( MPC_Scatter, MPI_COLL,  MPC_Scatter calls )
		PROBE( MPC_Scatterv, MPI_COLL,  MPC_Scatterv calls )
	PROBE( MPI_COMMUNICATORS, MPI, MPI Communicator calls )
		PROBE( MPC_Comm_create, MPI_COMMUNICATORS,  MPC_Comm_create calls )
		PROBE( MPC_Comm_create_list, MPI_COMMUNICATORS,  MPC_Comm_create_list calls )
		PROBE( MPC_Comm_dup, MPI_COMMUNICATORS,  MPC_Comm_dup calls )
		PROBE( MPC_Comm_free, MPI_COMMUNICATORS,  MPC_Comm_free calls )
		PROBE( MPC_Comm_split, MPI_COMMUNICATORS,  MPC_Comm_split calls )
	PROBE( MPI_GROUPS, MPI, MPI Group calls )
		PROBE( MPC_Comm_group, MPI_GROUPS,  MPC_Comm_group calls )
		PROBE( MPC_Group_difference, MPI_GROUPS,  MPC_Group_difference calls )
		PROBE( MPC_Group_free, MPI_GROUPS,  MPC_Group_free calls )
		PROBE( MPC_Group_incl, MPI_GROUPS,  MPC_Group_incl calls )
	PROBE( MPI_PACK, MPI, MPI Group calls )
		PROBE( MPC_Add_pack, MPI_PACK,  MPC_Add_pack calls )
		PROBE( MPC_Add_pack_absolute, MPI_PACK,  MPC_Add_pack_absolute calls )
		PROBE( MPC_Add_pack_default, MPI_PACK,  MPC_Add_pack_default calls )
		PROBE( MPC_Default_pack, MPI_PACK,  MPC_Default_pack calls )
		PROBE( MPC_Open_pack, MPI_PACK,  MPC_Open_pack calls )
	PROBE( MPI_RANK, MPI, MPI rank and context calls )
		PROBE( MPC_Node_number, MPI_RANK,  MPC_Node_number calls )
		PROBE( MPC_Node_rank, MPI_RANK,  MPC_Node_rank calls )
		PROBE( MPC_Process_number, MPI_RANK,  MPC_Process_number calls )
		PROBE( MPC_Process_rank, MPI_RANK,  MPC_Process_rank calls )
		PROBE( MPC_Processor_number, MPI_RANK,  MPC_Processor_number calls )
		PROBE( MPC_Processor_rank, MPI_RANK,  MPC_Processor_rank calls )
		PROBE( MPC_Comm_rank, MPI_RANK,  MPC_Comm_rank calls )
		PROBE( MPC_Comm_size, MPI_RANK,  MPC_Comm_size calls )
		PROBE( MPC_Get_processor_name, MPI_RANK,  MPC_Get_processor_name calls )
		PROBE( MPC_Get_count, MPI_RANK,  MPC_Get_count calls )
		PROBE( MPC_Wtime, MPI_RANK , MPC_Wtime calls )
	PROBE( MPI_ERROR, MPI, MPI error related calls )
		PROBE( MPC_Errhandler_create, MPI_ERROR,  MPC_Errhandler_create calls )
		PROBE( MPC_Errhandler_free, MPI_ERROR,  MPC_Errhandler_free calls )
		PROBE( MPC_Errhandler_get, MPI_ERROR,  MPC_Errhandler_get calls )
		PROBE( MPC_Errhandler_set, MPI_ERROR,  MPC_Errhandler_set calls )
		PROBE( MPC_Error_class, MPI_ERROR,  MPC_Error_class calls )
		PROBE( MPC_Error_string, MPI_ERROR,  MPC_Error_string calls )
		PROBE( MPC_Abort, MPI_ERROR,  MPC_Abort calls )
	PROBE( MPI_TYPES, MPI, MPI types related calls )
		PROBE( MPC_Sizeof_datatype, MPI_TYPES,  MPC_Sizeof_datatype calls )
		PROBE( MPC_Type_free, MPI_TYPES,  MPC_Type_free calls )
		PROBE( MPC_Type_size, MPI_TYPES,  MPC_Type_size calls )
		PROBE( MPC_Derived_datatype, MPI_TYPES,  MPC_Derived_datatype calls )
	PROBE( MPI_OP, MPI, MPI Operation related calls )
		PROBE( MPC_Op_create, MPI_OP , MPC_Op_create calls )
		PROBE( MPC_Op_free, MPI_OP , MPC_Op_free calls )
	PROBE( MPI_SETUP, MPI, MPI Init and release calls )
		PROBE( MPC_Finalize, MPI_SETUP , MPC_Finalize calls )
		PROBE( MPC_Init, MPI_SETUP , MPC_Init calls )
		PROBE( MPC_Initialized, MPI_SETUP , MPC_Initialized calls )

PROBE( ALLOCATOR, NO_PARENT, MPC Allocator calls )
	PROBE( malloc, ALLOCATOR,  malloc calls )
	PROBE( calloc, ALLOCATOR,  calloc calls )
	PROBE( realloc, ALLOCATOR,  realloc calls )
	PROBE( free, ALLOCATOR,  free calls )
	PROBE( sctk_malloc, ALLOCATOR,  sctk_malloc calls )
	PROBE( sctk_calloc, ALLOCATOR,  sctk_calloc calls )
	PROBE( sctk_realloc, ALLOCATOR,  sctk_realloc calls )
	PROBE( sctk_free, ALLOCATOR,  sctk_free calls )
	PROBE( sctk_sbrk, ALLOCATOR,  sctk_sbrk calls )
	PROBE( sctk_sbrk_try_to_find_page, ALLOCATOR,  sctk_sbrk_try_to_find_page calls )
	PROBE( sctk_sbrk_mmap, ALLOCATOR,  sctk_sbrk_mmap calls )
	PROBE( sctk_free_distant, ALLOCATOR,  sctk_free_distant calls )
	PROBE( sctk_mmap, ALLOCATOR,  sctk_mmap calls )
	PROBE( sctk_alloc_ptr_small_serach_chunk, ALLOCATOR,  sctk_alloc_ptr_small_serach_chunk calls )
	PROBE( sctk_alloc_ptr_big, ALLOCATOR,  sctk_alloc_ptr_big calls )
	PROBE( sctk_alloc_ptr_small, ALLOCATOR,  sctk_alloc_ptr_small calls )
	PROBE( sctk_free_small, ALLOCATOR,  sctk_free_small calls )
	PROBE( sctk_free_big, ALLOCATOR,  sctk_free_big calls )

PROBE( THREAD, NO_PARENT, MPI Thread calls )
	PROBE( sctk_thread_mutex_lock, THREAD,  sctk_thread_mutex_lock calls )
	PROBE( sctk_thread_mutex_unlock, THREAD,  sctk_thread_mutex_unlock calls )
	PROBE( sctk_thread_mutex_spinlock, THREAD,  sctk_thread_mutex_spinlock calls )
	PROBE( sctk_thread_wait_for_value_and_poll, THREAD,  sctk_thread_wait_for_value_and_poll calls )
	PROBE( sctk_thread_wait_for_value, THREAD,  sctk_thread_wait_for_value calls )

PROBE( MESSAGE_PASSING_INT, NO_PARENT, MPC Message passing internals )
	PROBE( sctk_elan_barrier, MESSAGE_PASSING_INT,  sctk_elan_barrier calls )
	PROBE( sctk_net_send_ptp_message_driver, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver calls )
	PROBE( sctk_net_get_new_header, MESSAGE_PASSING_INT,  sctk_net_get_new_header calls )
	PROBE( sctk_net_send_ptp_message_driver_inf, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_inf calls )
	PROBE( sctk_net_send_ptp_message_driver_sup, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_sup calls )
	PROBE( sctk_net_send_ptp_message_driver_sup_write, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_sup_write calls )
	PROBE( sctk_net_send_ptp_message_driver_split_header, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_split_header calls )
	PROBE( sctk_net_send_ptp_message_driver_send_header, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_send_header calls )


PROBE( OPEN_MP, NO_PARENT, MPC Message passing internals )
	PROBE( __sctk_microthread_parallel_exec__last_barrier , OPEN_MP,  __sctk_microthread_parallel_exec__last_barrier calls )
	PROBE( __mpcomp_start_parallel_region, OPEN_MP,  __mpcomp_start_parallel_region calls )
	PROBE( __mpcomp_start_parallel_region__creation, OPEN_MP,  __mpcomp_start_parallel_region__creation calls )
