# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
        exclude: .gitlab-ci.yml # Error caused by syntax "<<: *run_by_main"
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .gitlab/issue_templates/bugreport.md
-   repo: https://github.com/pocc/pre-commit-hooks.git
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        # Mute linker warning on unused flags "-Wl,-rpath=<mpc-install>/lib64"
        args: [--system-headers, --header-filter='.*', --extra-arg=-Wnounused-command-line-argument]
-   repo: git@gitlab.paratools.com:cea/mpc-pre-commit-hooks.git
    rev: 90dac57b3624db79877f93a59d218255463d708f
    hooks:
    -   id: git-blame-ignore-revs
exclude: |
  (?x)
    src/MPC_IO/src/romio|
    src/MPC_Common/include/mpc_common_profiler_keys.h|
    \.(m4|in|3in|f90)$
