# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-yaml
        exclude: .gitlab-ci.yml # Error caused by syntax "<<: *run_by_main"
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .gitlab/issue_templates/bugreport.md
-   repo: https://github.com/pocc/pre-commit-hooks.git
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        # Mute linker warning on unused flags "-Wl,-rpath=<mpc-install>/lib64"
        args: [--system-headers, --header-filter='.*', --extra-arg=-Wnounused-command-line-argument]
        exclude: |
          (?x)
            ^src/MPC_IO/src/romio|
            ^src/MPC_Common/include/mpc_common_profiler_keys\.h$|
            ^src/MPC_OpenMP/include/omp_lib\.h$|
            ^src/MPC_OpenMP/include/omp_lib_kinds\.h$|
            ^src/MPC_Fortran|
            ^src/MPC_Thread_db/src/gdb/linux-thread-db\.c$|
            ^src/MPC_Common/include/sctk_no_alloc\.h$|
            ^src/MPC_Tests/lcp|
            ^src/MPC_Thread_db/src/sctk_lib_thread_db\.c$|
            ^cmake/example/t.c$|
            \.(m4|in|3in|f90)$
          # 1. FIXME: Remove exclude path "src/MPC_Tests/lcp" once tests are fixed (LCP v2)
          # 2. sctk_lib_thread_db.c contains unmuteable false positives on "ambiguous" calls
          #    with #pragma weak and extern functions. This a known LLVM issue, see
          #    https://github.com/llvm/llvm-project/issues/16067
-   repo: git@gitlab.paratools.com:cea/mpc-pre-commit-hooks.git
    rev: v0.1.0
    hooks:
    -   id: git-blame-ignore-revs
