#!/bin/sh
##########################################################################
#            PROJECT  : MPC                                              #
#            VERSION  : 2.5.1                                            #
#            DATE     : 02/2014                                          #
#			 AUTHORS  : Sebastien Valat, Augustin Serraz, Jean-Yves Vet  #
#            LICENSE  : CeCILL-C                                         #
##########################################################################

ALL_PACKAGES=''
ALL_PACKAGES_HOST=''
ALL_PACKAGES_TARGET=''

#Default values
DOWNLOAD='disabled'
MIRROR='1'
MULTI_ARCH='false'
CHECK_INSTALL="true"
CHECK_DEPS="false"
SYSROOT_PATH="/"
MPCINSTALL_LIB_MODE='no'

######################################################
#Setup paths
PROJECT_BUILD_DIR=$PWD
PROJECT_SOURCE_DIR="`dirname "$0"`"
if [ "${PROJECT_SOURCE_DIR}" != "." ];
then
	PROJECT_SOURCE_DIR=$(cd `dirname "$0"` && pwd)
else 
	PROJECT_SOURCE_DIR="${PWD}"
fi

######################################################
#Include common
. "${PROJECT_SOURCE_DIR}/tools/Common.sh"

######################################################
#Set default configuration behavior
findCurrentArch 'MPC_HOST'
MPC_TARGET="${MPC_HOST}"
MPC_COMPILER="gcc"
MPC_GCC_PRIVATIZED_COMPILER="gcc"
MPC_GPP_PRIVATIZED_COMPILER="g++"
MPC_GFORT_PRIVATIZED_COMPILER="gfortran"

######################################################
#Compute subdirs
PROJECT_TEMPLATE_DIR="${PROJECT_SOURCE_DIR}/tools/templates"
PROJECT_PACKAGE_DIR="${PROJECT_SOURCE_DIR}/extern-deps"
PROJECT_PATCH_DIR="${PROJECT_SOURCE_DIR}/patches"
PROJECT_HELP_DIR="${PROJECT_SOURCE_DIR}/tools/help"

######################################################
#Check if colors could be enabled
if [ -t 1 ]; then
    ncolors=$(tput colors)
    if test -n "$ncolors" && test $ncolors -ge 8; then
	ENABLE_COLOR='true'
    fi
fi

######################################################
# Set all modules to internal
DEFAULT_DISABLED="tbb gdb dmtcp"
setModulesToInternal


USE_SPACK=0
SKIP_LIB_CHECK_SPACK=0
######################################################
#Parse options
for arg in "$@"
do
	case "$arg" in
		############### BUILD SPECIFIC ###############
		clean)
			echo "Cleaning everything but Makefile..."
			#Mark build dir
			if [ -f "${PROJECT_BUILD_DIR}/.mpcbuilddir" ];
			then
				cd ${PROJECT_BUILD_DIR}
				# RM...
				for arch in `find . -mindepth 1 -maxdepth 1 -type d`
				do
    				cd ${PROJECT_BUILD_DIR}/${arch}

    				#remove all hidden files used by makefile
    				for hfile in `find . -mindepth 1 -maxdepth 1 -type f | grep "\./\."`
    				do
    					rm ${hfile}
    				done
    				
    				#remove all packages
    				for package in `find . -mindepth 1 -maxdepth 1 -type d`
    				do
    					echo -n "  - removing $package build dir... "
    					rm -rf ${PROJECT_BUILD_DIR}/${arch}/${package} && echo "Done!"
    				done
				done
				exit 0
			else 
				echo "Wrong directory... abort"
				exit 1
			fi
			;;	
		distclean)
			echo -n "Cleaning ${PROJECT_BUILD_DIR}/* directories... "
			if [ -f "${PROJECT_BUILD_DIR}/.mpcbuilddir" ];
			then
				if [ -n "${PROJECT_BUILD_DIR}" ] && [ -d "${PROJECT_BUILD_DIR}" ];
				then
					rm -rf "${PROJECT_BUILD_DIR}"/* && rm "${PROJECT_BUILD_DIR}"/.mpcbuilddir && echo "Done !" || echo "Unable to clean ${PROJECT_BUILD_DIR}/* directories"
					exit 0
				fi
			else 
				echo "Wrong directory... abort"
				exit 1
			fi
			exit 0
			;;	
		############### DOWNLOAD DEPS ###############
		--mirror=*)
			extractParamValue 'MIRROR' 'mirror' "$arg"
			;;
		--download-missing-deps)
			DOWNLOAD='enabled'
			;;
		################# SCTK_ARCH #################
		--with-hydra=*)
			extractParamValue 'HYDRA_PREFIX' 'with-hydra' "$arg"
			;;
		--hydra-*)
			extractAndAddPackageOption 'HYDRA_BUILD_PARAMETERS' 'hydra' "$arg"
			;;
		--disable-mpc-hydra)
		    HYDRA_PREFIX='disabled'
			HYDRA_SIMPLE_PREFIX='disabled'
			;;  
		################# SCTK_ARCH #################
		--with-sctk-arch=*)
			extractParamValue 'SCTK_ARCH_PREFIX' 'with-sctk-arch' "$arg"
			;;
		--sctk-arch-*)
			extractAndAddPackageOption 'SCTK_ARCH_BUILD_PARAMETERS' 'sctk_arch' "$arg"
			;;
		#################### OPENPA #################
		--with-openpa=*)
			extractParamValue 'OPENPA_PREFIX' 'with-openpa' "$arg"
			;;
		--openpa-*)
			extractAndAddPackageOption 'OPENPA_BUILD_PARAMETERS' 'openpa' "$arg"
			;;
		################### MPC GDB #################
		--with-mpc-gdb=*)
			extractParamValue 'GDB_PREFIX' 'with-mpc-gdb' "$arg"
			;;
		--mpc-gdb-*)
			extractAndAddPackageOption 'GDB_BUILD_PARAMETERS' 'mpc-gdb' "$arg"
			;;
		--disable-mpc-gdb)
			GDB_PREFIX='disabled'
			;;
                --enable-mpc-gdb)
                        enableParamIfNot 'GDB_PREFIX' "$GDB_PREFIX" 'disabled' 'internal'
                        ;;

		################### MPC GCC #################
		--with-mpc-gcc=*)
			extractParamValue 'GCC_PREFIX' 'with-mpc-gcc' "$arg"
			;;
		--mpc-gcc-*)
			extractAndAddPackageOption 'GCC_BUILD_PARAMETERS' 'mpc-gcc' "$arg"
			;;
		--disable-mpc-gcc)
			GCC_PREFIX='disabled'
			LIBEXTLS_PREFIX="disabled"			
			SCTK_GETOPT_PREFIX='disabled'
			PRIV_PLUGIN_PREFIX='disabled'
			GMP_PREFIX='disabled'
			MPFR_PREFIX='disabled'
			MPC_PREFIX='disabled'
            # Be sure to use dy default GNU compilers
            # This can be overidden by --compiler= option
			COMPILER_ARG=yes
			;;
		################# FORTRAN GCC ###############
		--disable-mpc-fortran)
			FORTRAN_PREFIX='disabled'
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --disable-fortran"
			;;
		##################### MPFR ##################
		--with-mpfr=*)
			extractParamValue 'MPFR_PREFIX' 'with-mpfr' "$arg"
			;;
		--mpfr-*)
			extractAndAddPackageOption 'MPFR_BUILD_PARAMETERS' 'mpfr' "$arg"
			;;
		##################### GMP ###################
		--with-gmp=*)
			extractParamValue 'GMP_PREFIX' 'with-gmp' "$arg"
			;;
		--gmp-*)
			extractAndAddPackageOption 'GMP_BUILD_PARAMETERS' 'gmp' "$arg"
			;;
		################## BINUTILS #################
		--with-mpc-binutils=*)
			extractParamValue 'BINUTILS_PREFIX' 'with-mpc-binutils' "$arg"
			;;
		--mpc-binutils-*)
			extractAndAddPackageOption 'BINUTILS_BUILD_PARAMETERS' 'mpc-binutils' "$arg"
			;;
		--disable-mpc-binutils)
		    	BINUTILS_PREFIX='disabled'
		    	GCC_PREFIX="disablec"
			PRIV_PLUGIN_PREFIX='disabled'
			LIBEXTLS_PREFIX="disabled"			
			SCTK_GETOPT_PREFIX='disabled'
			;;  
		################## LIBXML2 ##################
		--with-libxml2=*)
			extractParamValue 'LIBXML2_PREFIX' 'with-libxml2' "$arg"
			;;
		--libxml2-*)
			extractAndAddPackageOption 'LIBXML2_BUILD_PARAMETERS' 'libxml2' "$arg"
			;;
		################### HWLOC ###################
		--with-hwloc=*)
			extractParamValue 'HWLOC_PREFIX' 'with-hwloc' "$arg"
			;;
		--hwloc-*)
			extractAndAddPackageOption 'HWLOC_BUILD_PARAMETERS' 'hwloc' "$arg"
			;;
		################### CUDA ###################
		--with-cuda=*)
			extractParamValue 'CUDA_PREFIX' 'with-cuda' "$arg"
			;;
		--with-openacc=*)
			extractParamValue 'OPENACC_PREFIX' 'with-openacc' "$arg"
			;;
		--with-opencl=*)
			extractParamValue 'OPENCL_PREFIX' 'with-opencl' "$arg"
			;;
		################### TBB ###################
		--with-tbb=*)
			extractParamValue 'TBB_PREFIX' 'with-tbb' "$arg"
			;;
		--tbb-*)
			extractAndAddPackageOption 'TBB_BUILD_PARAMETERS' 'tbb' "$arg"
			;;
		--enable-mpc-tbb)
			enableParamIfNot 'TBB_PREFIX' "$TBB_PREFIX" 'disabled' 'internal'
			;;
		--disable-mpc-tbb)
			TBB_PREFIX="disabled"
			;;
		################### EXTLS ###################
		--with-libextls=*)
			extractParamValue 'LIBEXTLS_PREFIX' 'with-libextls' "$arg"
			;;
		--libextls-*)
			extractAndAddPackageOption 'LIBEXTLS_BUILD_PARAMETERS' 'libextls' "$arg"
			;;
		################### HBICT ###################
		--with-hbict=*)
			extractParamValue 'HBICT_PREFIX' 'with-hbict' "$arg"
			;;
		--hbict-*)
			extractAndAddPackageOption 'HBICT_BUILD_PARAMETERS' 'hbict' "$arg"
			;;
		################### DMTCP ###################
		--with-dmtcp=*)
			extractParamValue 'DMTCP_PREFIX' 'with-dmtcp' "$arg"
			;;
		--dmtcp-*)
			extractAndAddPackageOption 'DMTCP_BUILD_PARAMETERS' 'dmtcp' "$arg"
			;;
		################### GENERIC FT ###################
		--enable-mpc-ft)
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --enable-MPC_Fault_Tolerance"
			enableParamIfNot 'DMTCP_PREFIX' "$DMTCP_PREFIX" 'disabled' 'internal'
			;;
		--disable-mpc-ft)
			DMTCP_PREFIX="disabled"
			;;
		################# COMPILER ##################
		--compiler=*)
			extractParamValue 'MPC_COMPILER' 'compiler' "$arg"
			COMPILER_ARG=yes
			;;
		############### MPCFRAMEWORK ################
		--mpc-option=*)
			extractAndAddPackageOption 'MPCFRAMEWORK_BUILD_PARAMETERS' 'mpc-option=' "$arg"
			;;
		--enable-color)
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --enable-shell-colors"
			LIBEXTLS_BUILD_PARAMETERS="${LIBEXTLS_BUILD_PARAMETERS} --enable-color"
			;;
		--enable-mpc-debug)
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --enable-debug --enable-debug-messages"
			enableParamIfNot 'GDB_PREFIX' "$GDB_PREFIX" 'disabled' 'internal'
			;;
		--with-slurm)
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --with-slurm"
			;;
		--disable-MPC_MPI)
			ROMIO_PREFIX='disabled'		
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --disable-MPC_MPI"
			;;
		--disable-ROMIO|--disable-romio)
			ROMIO_PREFIX='disabled'
			;;
		--lib-mode)
			ROMIO_PREFIX='disabled'
			TBB_PREFIX='disabled'
			GDB_PREFIX='disabled'
			MPC_PREFIX='disabled'
			GCC_PREFIX='disabled'
			#LIBEXTLS_PREFIX='disabled'
			PRIV_PLUGIN_PREFIX='disabled'
			HYDRA_PREFIX='disabled'
			HYDRA_SIMPLE_PREFIX='disabled'
			GMP_PREFIX='disabled'
			MPFR_PREFIX='disabled'
			BINUTILS_PREFIX='disabled'
			SCTK_GETOPT_PREFIX='disabled'
			MPC_MPIT_PREFIX='disabled'
			MPL_PREFIX='disabled'
			MPCINSTALL_LIB_MODE='yes'
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --disable-MPC_MPI --disable-MPC_Allocator --enable-lib-mode"
			#special case, when installmpc does not handle any available compiler
			#by default, GCC compiler will be used, this behavior can be altered through the --compiler= option
			COMPILER_ARG=yes
			;;
		--mpc-process-mode)			
			GCC_PREFIX='disabled'
			PRIV_PLUGIN_PREFIX='disabled'
			LIBEXTLS_PREFIX='disabled'
			GMP_PREFIX='disabled'
			MPFR_PREFIX='disabled'
			MPC_PREFIX='disabled'
			BINUTILS_PREFIX='disabled'
			SCTK_GETOPT_PREFIX='disabled'
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} --enable-process-mode"
			#special case, when installmpc does not handle any available compiler
			#by default, GCC compiler will be used, this behavior can be altered through the --compiler= option
			COMPILER_ARG=yes
			;;
		##################### MPC ###################
		--with-mpc=*)
			extractParamValue 'MPC_PREFIX' 'with-mpc' "$arg"
			;;
		--mpc-*)
			extractAndAddPackageOption 'MPC_BUILD_PARAMETERS' 'mpc' "$arg"
			;;
		############### CROSS-COMPIL ################
		--host=*)
			extractArchValue 'MPC_HOST' 'host' "$arg"
			export MPC_HOST
			;;
		--target=*)
			extractArchValue 'MPC_TARGET' 'target' "$arg"
			export MPC_TARGET
			export MPC_HOST
			;;
		--arch-library-path=*)
			ARCH_LIBRARY_PATH="${arg}"
			MPCFRAMEWORK_BUILD_PARAMETERS="${MPCFRAMEWORK_BUILD_PARAMETERS} ${ARCH_LIBRARY_PATH}"
		;;
        --with-sysroot=*)
            extractParamValue 'SYSROOT_PATH' 'with-sysroot' "$arg"
        ;;
		################## COMMON ###################
		--enable-check-deps)
			CHECK_DEPS="true"
			;;
		--disable-check-deps)
			CHECK_DEPS="false"
			;;
		--disable-check-install)
			CHECK_INSTALL="false"
			;;
		--disable-color)
			ENABLE_COLOR='false'
			;;
		--enable-all-internals)
			ALL_INTERNALS='true'
			;;
		-v | --verbose | --verbose=1)
			STEP_WRAPPER_VERBOSE=1
			export STEP_WRAPPER_VERBOSE
			;;
		-vv | --verbose=2)
			STEP_WRAPPER_VERBOSE=2
			export STEP_WRAPPER_VERBOSE
			;;
		-vvv | --verbose=3)
			STEP_WRAPPER_VERBOSE=3
			export STEP_WRAPPER_VERBOSE
			;;
		-j*)
			extractParamValueAlt 'MAKE_J' 'j' "$arg"
			;;
		--prefix=*)
			extractParamValue 'PREFIX' 'prefix' "$arg"
			MPC_RPREFIX="${PREFIX}"
			export MPC_RPREFIX
			#Check if prefix directory exists
			if [ ! -d "${PREFIX}" ]; then
				mkdir -p ${PREFIX}
			fi
			;;
		--help|-h|-?)
			showHelp
			;;
		--version)
			showVersion
			;;
		--spack)
			USE_SPACK=1
			SKIP_LIB_CHECK_SPACK=1
			;;
		--spack-build)
			SKIP_LIB_CHECK_SPACK=1
			;;
		*)
			echo "Invalid argument '$arg', please check your command line or get help with --help." 1>&2
			exit 1
	esac
done

check_spack_package(){
if test "$USE_SPACK" = "1"; then
	output_var="$1"
	name="$2"
	eval "val=\$${output_var}"
#	echo "SPACK mode for $name $val"
	if test "$val" = "internal"; then 
		TMP_PREFIX="`spack location --install-dir $name 2> /dev/null`"
		if test "$TMP_PREFIX" != "" ; then 
			eval "${output_var}=\"$TMP_PREFIX\""
		fi	
	fi	
fi
}
check_spack_package 'HYDRA_PREFIX' 'hydra'
check_spack_package 'HWLOC_PREFIX' 'hwloc'
check_spack_package 'LIBXML2_PREFIX' 'libxml2'
check_spack_package 'GMP_PREFIX' 'gmp'
check_spack_package 'MPFR_PREFIX' 'mpfr'
check_spack_package 'MPC_PREFIX' 'mpc'
check_spack_package 'GCC_PREFIX' 'mpc-gcc'
check_spack_package 'GDB_PREFIX' 'mpc-gdb'
check_spack_package 'BINUTILS_PREFIX' 'mpc-binutils'

#######################################################
# Check for dependencies
if test "${CHECK_DEPS}" = "true";
then 
	package_list=""
	if test "${HYDRA_PREFIX}" = "disabled"; 
	then
		${PROJECT_SOURCE_DIR}/check_deps --with-slurm > deps_result.txt
	else
		${PROJECT_SOURCE_DIR}/check_deps > deps_result.txt
	fi
	if test "${GCC_PREFIX}" != "disabled"; then
		package_list="gcc"
	fi
	if test "${GDB_PREFIX}" != "disabled"; then
		package_list="${package_list} gdb"
	fi
	package_list="${package_list} infiniband"

	check_dependencies "${package_list}"
	if test -f "deps_result.txt"; then 
		rm deps_result.txt
	fi
fi

#######################################################
# Avoid to build locally
if [ "${PROJECT_BUILD_DIR}" = "${PROJECT_SOURCE_DIR}" ]; 
then
	#check if build directory exist
	if [ ! -d "${PWD}/build" ];
	then
		mkdir -p build
	fi
	PROJECT_BUILD_DIR="${PWD}/build"
	PROJECT_SOURCE_DIR="${PWD}"
	cd build
fi

######################################################
#Check if install is already there or not writable
if test ! -w $PREFIX; then
	echo "#######################################################################"
	echo "# Installation prefix '$PREFIX' has no write permission access."
	echo "# Please make it writable or change it with --prefix option."
	echo "#######################################################################"
	exit 3
fi

if test "${CHECK_INSTALL}" = "true"; then
	checkIfInstallAlreadyExists
else
	cleanExistingInstall
fi

######################################################
#Check for specific arch libs
if test "${MPC_TARGET}" = "k1om"; then
	if test "${ARCH_LIBRARY_PATH}" = ""; then
		echo "##########################################################################################"
		echo "# You must use --arch-library-path=* to specify the path of the k1om specific libraries. #"
		echo "# Example: --arch-library-path=/opt/intel/composer_xe_2013.4.183/compiler/libs/mic       #"
		echo "##########################################################################################"
		exit 1
	fi
fi

######################################################
#Add prefix to local variable to also make the search
enablePrefixEnv "${PREFIX}"

######################################################
MPCFRAMEWORK_PREFIX="${INTERNAL_KEY}"
GMP_INTERNAL_PREFIX="${PREFIX}/${MPC_HOST}/${MPC_HOST}/libsgcc"
MPFR_INTERNAL_PREFIX="${PREFIX}/${MPC_HOST}/${MPC_HOST}/libsgcc"
MPC_INTERNAL_PREFIX="${PREFIX}/${MPC_HOST}/${MPC_HOST}/libsgcc"

######################################################
#Fill MPC Build parameters
fillGCCBuildParameters()
{
	#Verify if users give path for gmp
	if test -z "${GMP_PREFIX}" -o "${GMP_PREFIX}" = "internal"; then
		MPFR_BUILD_PARAMETERS="'--with-gmp=${GMP_INTERNAL_PREFIX}' ${MPFR_BUILD_PARAMETERS}"
		MPC_BUILD_PARAMETERS="'--with-gmp=${GMP_INTERNAL_PREFIX}' ${MPC_BUILD_PARAMETERS}"
	else
		MPFR_BUILD_PARAMETERS="'--with-gmp=${GMP_PREFIX}' ${MPFR_BUILD_PARAMETERS}"
		MPC_BUILD_PARAMETERS="'--with-gmp=${GMP_PREFIX}' ${MPC_BUILD_PARAMETERS}"
		export GMP_PREFIX
	fi
	#Verify if users give path for mpfr
	if test -z "${MPFR_PREFIX}" -o "${MPFR_PREFIX}" = "internal"; then
		MPC_BUILD_PARAMETERS="--with-mpfr=${MPFR_INTERNAL_PREFIX} ${MPC_BUILD_PARAMETERS}"
	else
		MPC_BUILD_PARAMETERS="--with-mpfr=${MPFR_PREFIX} ${MPC_BUILD_PARAMETERS}"
	fi
	#Verify if users give path for mpc
	if test -z "${MPC_PREFIX}" -o "${MPC_PREFIX}" != "internal"; then
		GCC_BUILD_PARAMETERS="'--with-mpc=${MPC_PREFIX}' ${GCC_BUILD_PARAMETERS}"
	fi
	
	version="`cat ${PROJECT_SOURCE_DIR}/config.txt | grep "^\s*gcc\s*;" | cut -f 2 -d ';' | sed -e 's/\.//g' | xargs echo`"
	GCC_BUILD_PARAMETERS="--program-prefix=mpc- --program-suffix=_${version} --with-pkgversion=MPC --enable-languages=c,c++,fortran --disable-bootstrap --disable-multilib ${GCC_BUILD_PARAMETERS}"

	if test "$GCC_PREFIX" = "internal" ; then 
		MPC_GCC_PRIVATIZED_COMPILER="${PREFIX}/${MPC_HOST}/${MPC_HOST}/bin/mpc-gcc_${version}"
		export MPC_GCC_PRIVATIZED_COMPILER

		MPC_GPP_PRIVATIZED_COMPILER="${PREFIX}/${MPC_HOST}/${MPC_HOST}/bin/mpc-g++_${version}"
		export MPC_GPP_PRIVATIZED_COMPILER
	
		MPC_GFORT_PRIVATIZED_COMPILER="${PREFIX}/${MPC_HOST}/${MPC_HOST}/bin/mpc-gfortran_${version}"
		export MPC_GFORT_PRIVATIZED_COMPILER
	else
		MPC_GCC_PRIVATIZED_COMPILER="${GCC_PREFIX}/bin/mpc-gcc_${version}"
		export MPC_GCC_PRIVATIZED_COMPILER

		MPC_GPP_PRIVATIZED_COMPILER="${GCC_PREFIX}/bin/mpc-g++_${version}"
		export MPC_GPP_PRIVATIZED_COMPILER
	
		MPC_GFORT_PRIVATIZED_COMPILER="${GCC_PREFIX}/bin/mpc-gfortran_${version}"
		export MPC_GFORT_PRIVATIZED_COMPILER
	fi
}

######################################################
#Fill GCC Build parameters
fillMPCBuildParameters()
{
	#Verify if users give path for hwloc
	if test -z "${HWLOC_PREFIX}" -o "${HWLOC_PREFIX}" = "internal"; then
		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-hwloc=\$\(PREFIX\)/' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	else
		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-hwloc=${HWLOC_PREFIX}' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	fi
	#Verify if users give path for openpa
	if test -z "${OPENPA_PREFIX}" -o "${OPENPA_PREFIX}" = "internal"; then
		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-openpa=\$\(PREFIX\)/' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	else
		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-openpa=${OPENPA_PREFIX}' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	fi
	#verify if users give path for libxml2
	if test -z "${LIBXML2_PREFIX}" -o "${LIBXML2_PREFIX}" = "internal"; then
		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-libxml2.0=\$\(PREFIX\)/' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	else
		MPCFRAMEWORK_BUILD_PARAMETERS="'--with-libxml2.0=${LIBXML2_PREFIX}' ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	fi

	if test "${CUDA_PREFIX}" = "internal"; then
		echo "CUDA libraries are not embedded inside MPC ! Abort..."
		exit 1
	elif test -n "${CUDA_PREFIX}"; then
		MPCFRAMEWORK_BUILD_PARAMETERS="--with-cuda=${CUDA_PREFIX} ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	fi
	
	if test "${OPENACC_PREFIX}" = "internal"; then
		echo "OpenAcc implementation is not internally handled by MPC yet !"
		exit 1
	elif test -n "${OPENACC_PREFIX}"; then
		MPCFRAMEWORK_BUILD_PARAMETERS="--with-openacc=${OPENACC_PREFIX} ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	fi
	
	if test "${OPENCL_PREFIX}" = "internal"; then
		echo "OpenCL libraries are not embedded with MPC yet !"
		exit 1
	elif test -n "${OPENCL_PREFIX}"; then
		MPCFRAMEWORK_BUILD_PARAMETERS="--with-opencl=${OPENCL_PREFIX} ${MPCFRAMEWORK_BUILD_PARAMETERS}"
	fi
}

######################################################
#fill libextls Build parameters
fillTLSBuildParameters()
{
	#Verify if users give path for hwloc
	if test -z "${HWLOC_PREFIX}" -o "${HWLOC_PREFIX}" = "internal"; then
		LIBEXTLS_BUILD_PARAMETERS="'--with-hwloc=\$\(PREFIX\)/' ${LIBEXTLS_BUILD_PARAMETERS}"
	else
		LIBEXTLS_BUILD_PARAMETERS="'--with-hwloc=${HWLOC_PREFIX}' ${LIBEXTLS_BUILD_PARAMETERS}"
	fi
	#Verify if users give path for openpa
	if test -z "${OPENPA_PREFIX}" -o "${OPENPA_PREFIX}" = "internal"; then
		LIBEXTLS_BUILD_PARAMETERS="'--with-openpa=\$\(PREFIX\)/' ${LIBEXTLS_BUILD_PARAMETERS}"
	else
		LIBEXTLS_BUILD_PARAMETERS="'--with-openpa=${OPENPA_PREFIX}' ${LIBEXTLS_BUILD_PARAMETERS}"
	fi
}

######################################################
#Fill some external package options
fillTLSBuildParameters
fillGCCBuildParameters
fillMPCBuildParameters

######################################################
#Set build compiler in MPC_COMPILER
setBuildCompiler 

genMakefilePerType()
{
	applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.head.in" > ${makefilePath}
	for module in ${list}; 
	do
		template=`cat "${PROJECT_SOURCE_DIR}/config.txt" | grep "^${module} " | cut -f 8 -d ';' | xargs echo`
		run_on=`cat "${PROJECT_SOURCE_DIR}/config.txt" | grep "^${module} " | cut -f 6 -d ';' | xargs echo`
		if [ "${run_on}" = "${type_arch}" ] || [ "${run_on}" = "all" ];
		then
			if test "${type_arch}" = "host"; then
				RUN_ON="${MPC_HOST}"
			else
				RUN_ON="${MPC_TARGET}"
			fi
			UPPER=`echo ${module} | tr '[:lower:]' '[:upper:]'`
			findPackage "${module}"
			tmp=`echo "$LD_LIBRARY_PATH" | grep "${MPC_RPREFIX}/${MPC_HOST}/${MPC_TARGET}/lib"`
			if test "${tmp}" = ""; then
				LD_LIBRARY_PATH="${MPC_RPREFIX}/${MPC_HOST}/${MPC_TARGET}/lib:$LD_LIBRARY_PATH"
				export LD_LIBRARY_PATH
			fi
			setupInstallPackage "${module}" "${MPC_HOST}" "${MPC_TARGET}" "${MPC_COMPILER}" "${UPPER}" "${template}" "${2}">> ${makefilePath}
		fi
	done
	applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.foot_${type_arch}.in" >> ${makefilePath}
}

#####################################################
# generate Makefiles
genMakefile()
{
	list=`cat "${PROJECT_SOURCE_DIR}/config.txt" | cut -f 1 -d ';' |  sed -e "s/^#.*//g" | xargs echo`
	
	#Check if Makefile exists
	if [ -f "Makefile" ]; then
		echo "Makefile already generated. Use 'distclean' argument to regenerate it."
		echo "Continuing..."

	#Else create Makefiles
	else
		#############
		#Host case
		type_arch="host"

		#Create subdirectories and update subprefix 
		mkdir -p "${MPC_HOST}/${MPC_TARGET}" || exit 1
		cd "${MPC_HOST}/${MPC_TARGET}" || exit 1
		SUBPREFIX="/${MPC_HOST}/${MPC_TARGET}"
		makefilePath="Makefile.${type_arch}_${MPC_HOST}"

		genMakefilePerType
		#Generate root architecture for current type
		MAKEFILEDIR="${PROJECT_BUILD_DIR}${SUBPREFIX}"
		MAKEFILENAME="${makefilePath}"
		cat "${PROJECT_TEMPLATE_DIR}/Makefile.root_arch.head.in" > ${PROJECT_BUILD_DIR}/${MPC_HOST}/Makefile
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.root_arch.in" >> ${PROJECT_BUILD_DIR}/${MPC_HOST}/Makefile

		#Restore current path
		cd ${PROJECT_BUILD_DIR}

		#############
		#Target case
		type_arch="target"

		#Create subdirectories and update subprefix 
		mkdir -p "${MPC_TARGET}/${MPC_TARGET}" || exit 1
		cd "${MPC_TARGET}/${MPC_TARGET}" || exit 1
		SUBPREFIX="/${MPC_TARGET}/${MPC_TARGET}"
		makefilePath="Makefile.${type_arch}_${MPC_TARGET}"

		genMakefilePerType
		#Generate root architecture for current type
		MAKEFILEDIR="${PROJECT_BUILD_DIR}${SUBPREFIX}"
		MAKEFILENAME="${makefilePath}"
		if [ "${MPC_HOST}" != "${MPC_TARGET}" ];
		then
			cat "${PROJECT_TEMPLATE_DIR}/Makefile.root_arch.head.in" > ${PROJECT_BUILD_DIR}/${MPC_TARGET}/Makefile
		fi
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.root_arch.in" >> ${PROJECT_BUILD_DIR}/${MPC_TARGET}/Makefile
	fi
	
	#Restore current path
	cd ${PROJECT_BUILD_DIR}
}

######################################################
# Create root Makefile
createRootMakefile()
{
	if [ "${MPC_HOST}" = "${MPC_TARGET}" ];
	then
		SUBPREFIXES="${MPC_HOST}"
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.multiprefix.root.in" > Makefile
		TARGETNAME="${MPC_HOST}"
		TARGETDEP=""
		MAKEFILEDIR="${PROJECT_BUILD_DIR}/${TARGETNAME}"
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.multiprefix.subprefix.in" >> Makefile
	else
		SUBPREFIXES="${MPC_HOST} ${MPC_TARGET}"
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.multiprefix.root.in" > Makefile

		#Host case
		TARGETNAME="${MPC_HOST}"
		MAKEFILEDIR="${PROJECT_BUILD_DIR}/${TARGETNAME}"
		TARGETDEP=""
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.multiprefix.subprefix.in" >> Makefile

		#Target case
		TARGETNAME="${MPC_TARGET}"
		MAKEFILEDIR="${PROJECT_BUILD_DIR}/${TARGETNAME}"
		TARGETDEP="${MPC_HOST}"
		applyOnTemplate "${PROJECT_TEMPLATE_DIR}/Makefile.multiprefix.subprefix.in" >> Makefile
	fi
}

######################################################
# Determine host architecture
if [ "${MPC_HOST}" = "" ]; then
	findCurrentArch 'MPC_HOST'
fi

######################################################
#Print some info about parallel building
if [ ! -z "$MAKE_J" ]; then
	echo "Running in parallel with -j${MAKE_J}..."
else 
	#Check cores available and display info to perform parallel builds
	if [ -f /proc/cpuinfo ];
	then
		MAKE_J_AVAILABLE=`cat /proc/cpuinfo | egrep "core id|physical id" | tr -d '\n' | sed s/physical/\\\nphysical/g | grep -v "^$" | sort | uniq | wc -l`
		if [ "${MAKE_J_AVAILABLE}" -gt "1" ]; then 
			echo "Warning: this install script is running sequentially. However ${MAKE_J_AVAILABLE} physical cores were detected on your system. This installation could run faster. Use -j argument (e.g. -j${MAKE_J_AVAILABLE}) to perform a parallel build."
		fi
	fi
fi

######################################################
printSummary
checkBasics
genMakefile
createRootMakefile

#Create the MPC env run file 
applyOnTemplate "${PROJECT_TEMPLATE_DIR}/mpc_env.sh.in" > ${PROJECT_BUILD_DIR}/mpc_env.sh
chmod +x  ${PROJECT_BUILD_DIR}/mpc_env.sh


#Made verbose if seq
if [ "$MAKE_J" = "1" ] || [ -z "$MAKE_J" ]; then
	if [ -z "$STEP_WRAPPER_VERBOSE" ]; then 
		STEP_WRAPPER_VERBOSE=3
		export STEP_WRAPPER_VERBOSE  
	fi
fi

#Mark build dir
if [ ! -f "${PROJECT_BUILD_DIR}/.mpcbuilddir" ]; then
	touch "${PROJECT_BUILD_DIR}/.mpcbuilddir"
fi

#Do it
cd ${PROJECT_BUILD_DIR}
if [ "$STEP_WRAPPER_VERBOSE" = '3' ]; then
	make -j$MAKE_J || fatal "Finish with errors, please read previous messages."
else
	make --quiet -j$MAKE_J || fatal "Finish with errors, please read previous messages."
fi

######################################################
cp ${PROJECT_SOURCE_DIR}/tools/Architectures.sh ${PREFIX}/.Architectures.sh
cp ${PROJECT_SOURCE_DIR}/.config.arch.txt ${PREFIX}/.config.arch.txt
sed -i -e "s/PROJECT_SOURCE_DIR/MPC_INSTALL_DIR_PREFIX/g" ${PREFIX}/.Architectures.sh

#Generate main mpcvars.sh
applyOnTemplate "${PROJECT_TEMPLATE_DIR}/mpcvars.sh.in" > "${PREFIX}/mpcvars.sh"

#generate main mpcvars.csh
applyOnTemplate "${PROJECT_TEMPLATE_DIR}/mpcvars.csh.in" > "${PREFIX}/mpcvars.csh"

######################################################
#Put the new install in the list
putNewInstall

if test "$MPCINSTALL_LIB_MODE" = "no"; then
storeMPCcompilers
fi

######################################################
echo
echo "FINISHED, you can now use the MPC package installed into ${PREFIX}"
echo "You must source "source ${PREFIX}/mpcvars.sh" to load the environment variables for the system"
echo "You can choose a target environment with the command source ${PREFIX}/mpcvars.sh 'target'"
