#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#                                                                      #
########################################################################

cat <<EOF > $MPC_USE_MPCRC_FILE
###########################################################
#                 MPC default configuration               #
###########################################################

#Define default thread type (ethread/ethread_mxn/pthread)
#THREAD_TYPE="ethread_mxn"

#Define default network type (none/mpi)
NET_TYPE="none"

#Define show version details (yes/no)
VERSION_DETAILS="no"

#Define show report details (yes/no)
REPORT="no"

#Define enable checkpoint mode (yes/no)
CHECKPOINT="no"

#Define enable migration mode (yes/no)
MIGRATION="no"

#Define default task number
TASK_NB="1"

#Define default CPU number
CPU_NB="1"

#Define default process number
PROCESS_NB="1"

#Define default node number
NODE_NB="1"

#Define default launcher
LAUNCH="mpiexec"

#Define environnement variables that need propagation using space separator
MPC_ENVIRONNEMENT_PROPAGATE=""
EOF
