#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#                                                                      #
########################################################################

begin_section Generate mpc_ldflags

mkdir -p bin

cat <<EOF > bin/mpc_ldflags
#!/bin/sh
EOF

header_sh >> bin/mpc_ldflags


cat <<EOF >> bin/mpc_ldflags


FLAGS="-Wl,-rpath,${SCTK_LIB_DIR} -Wl,-rpath,${SCTK_LIB_DIR}/../lib64 -lmpc_tdb_remote_static $SCTK_LDFLAGS "

if test "\$MPC_USE_INTEL_COMPILER" = "1"; then
MPC_DO_NOT_USE_GNU_LM="1"
fi 

if test "\$MPC_DO_NOT_USE_GNU_LM" = "1"; then
NEW_FLAGS=""
for i in \$FLAGS; do
if test "\$i" = "-lm" ; then
NEW_FLAGS="\$NEW_FLAGS"
else
NEW_FLAGS="\$NEW_FLAGS '\$i'"
fi
done
FLAGS="\$NEW_FLAGS"
fi

if test "\$1" != "fortran" ; then
echo "-L${SCTK_LIB_DIR} -lmpc_framework \$FLAGS"
else
echo "-L${SCTK_LIB_DIR} -lmpc_frameworkf \$FLAGS"
fi
EOF

chmod 755 bin/mpc_ldflags

end_section
