#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#                                                                      #
########################################################################
begin_section Generate mpc_cflags

mkdir -p bin

cat <<EOF > bin/mpc_cflags
#!/bin/sh
EOF

header_sh >> bin/mpc_cflags

FLAGS=""
for i in $MODULE_LIST; do
FLAGS="$FLAGS -DMPC_MODULE_$i"
done

#This flag is set in MPC_Common sysdep for MPC AIO
if test "x$MPC_AIO_ENABLED" = "x1"; then
		FLAGS="$FLAGS  -DMPC_AIO_ENABLED"
fi

#This flag is set when MPC runs in lib-mode
if test "x$SCTK_LIB_MODE" = "x1"; then
		FLAGS="$FLAGS  -DSCTK_LIB_MODE"
fi

cat <<EOF >> bin/mpc_cflags
ROMIO=""

#Only use romio if it is intalled
#because we use the same compiler
#to build romio itself
if test -e "${SCTK_LIB_DIR}/libromio.a"; then
	if test "x\${MPC_BOOTSTRAP}" != "xyes"; then
		ROMIO="-DMPC_ROMIO_ENABLED"
	fi
fi
EOF

cat <<EOF >> bin/mpc_cflags
SCTK_GETOPT=""

if test -e "${SCTK_LIB_DIR}/libmpcgetopt.a"; then
	if test "x\${MPC_BOOTSTRAP}" != "xyes"; then
		SCTK_GETOPT="-DMPC_GETOPT_ENABLED"
	fi
fi
EOF

cat <<EOF >> bin/mpc_cflags
if test "\$1" != "fortran" ; then
EOF
if test "${SCTK_MIC}" = "1" ; then
cat <<EOF >> bin/mpc_cflags
echo "-I${SCTK_INCLUDE_DIR} -I${SCTK_INCLUDE_DIR}/../ \$ROMIO \${SCTK_GETOPT} $FLAGS -L${SCTK_ARCH_LIBRARY_PATH} -Wl,-rpath=${SCTK_ARCH_LIBRARY_PATH} "
EOF
else
#${SCTK_LIB_DIR}/mpi_sizeofs.o defines the Fortran MPI_SIZEOF implementation
cat <<EOF >> bin/mpc_cflags

echo "-I${SCTK_INCLUDE_DIR} -I${SCTK_INCLUDE_DIR}/../ \$ROMIO \${SCTK_GETOPT} $FLAGS "
EOF
fi

cat <<EOF >> bin/mpc_cflags
else
EOF

if test "${SCTK_MIC}" = "1" ; then
cat <<EOF >> bin/mpc_cflags
echo "-I${SCTK_INCLUDE_DIR} -I${SCTK_INCLUDE_DIR}/../ \$ROMIO \${SCTK_GETOPT} $FLAGS -L${SCTK_ARCH_LIBRARY_PATH} -Wl,-rpath=${SCTK_ARCH_LIBRARY_PATH}"
EOF
else
cat <<EOF >> bin/mpc_cflags
echo "-I${SCTK_INCLUDE_DIR} -I${SCTK_INCLUDE_DIR}/../ \$ROMIO \${SCTK_GETOPT} $FLAGS"
EOF
fi

cat <<EOF >> bin/mpc_cflags
fi
EOF

chmod 755 bin/mpc_cflags

end_section
