#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PULVERAIL Sebastien sebastien.pulverail@sogeti.com               #
#                                                                      #
########################################################################

begin_section Generate mpc_edit_config
mkdir -p bin

echo "#!/bin/sh" > bin/mpc_edit_config
header_sh >> bin/mpc_edit_config

cat <<EOF >> bin/mpc_edit_config

prefix=${SCTK_PREFIX}
MPC_BIN_DIR=${SCTK_BIN_DIR}
MPC_LIB_DIR=${SCTK_LIB_DIR}
MPC_SHARE_DIR=${SCTK_SHARE_DIR}
MPC_SHARE_ED_DIR=${SCTK_SHARE_ED_DIR}
MPC_INCLUDE_DIR=${SCTK_INCLUDE_DIR}

EOF

cat ${MPC_SOURCE_DIR}MPC_Tools/mpc_edit_config_common >> bin/mpc_edit_config

chmod 755 bin/mpc_edit_config

end_section
