#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#                                                                      #
########################################################################

begin_section Generate mpcrun
mkdir -p bin

echo "#!/bin/sh" > bin/mpcrun
header_sh >> bin/mpcrun

cat <<EOF >> bin/mpcrun

prefix=${SCTK_PREFIX}
exec_prefix=${SCTK_PREFIX}/bin
MPC_BIN_DIR=${SCTK_BIN_DIR}
MPC_LIB_DIR=${SCTK_LIB_DIR}
MPC_SHARE_DIR=${SCTK_SHARE_DIR}
MPC_INCLUDE_DIR=${SCTK_INCLUDE_DIR}
SCTK_NET_LIST="$SCTK_NET_LIST"
SCTK_NET_LIST_EXP="$SCTK_NET_LIST_EXP"
SCTK_JOB_MANAGER="$SCTK_JOB_MANAGER"
DEBUGGER_LIST="$DEBUGGER_LIST"
EOF

#setup complete hydra path. Exported to be used into mpcrun_opt/* scripts
if [ $SCTK_HYDRA -eq 1 ] && [ ! -z "$SCTK_HYDRA_PREFIX" ]; then
	echo "export SCTK_HYDRA_BINDIR=\"${SCTK_PREFIX}/../hydra/bin/\"" >> bin/mpcrun
	echo "export PATH=\"\${SCTK_HYDRA_BINDIR}:\${PATH}\"" >> bin/mpcrun
	echo >> bin/mpcrun
fi

cat ${MPC_SOURCE_DIR}.MPC_version >> bin/mpcrun
cat ${MPC_SOURCE_DIR}MPC_Tools/mpcrun_common >> bin/mpcrun

chmod 755 bin/mpcrun

end_section
