#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#   - CARRIBAULT Patrick patrick.carribault@cea.fr                     #
#                                                                      #
########################################################################

#
# Generate the script to update environment according to MPC
# (for SH and CSH)
#

OUTPUT_FILE=bin/mpcvars.sh
ARCH=`uname -m`
begin_section Generate Environment Script ${OUTPUT_FILE}

echo "CONFIGURE ENV MPCROOT=${SCTK_PREFIX}"

# Header
echo "#!/bin/sh" > ${OUTPUT_FILE}
header_sh >> ${OUTPUT_FILE}


#if test "${MPC_HOST}" = "${ARCH}" ; then
cat <<EOF >> ${OUTPUT_FILE}
MPCROOT="`echo \"\\${MPC_RPREFIX}/${MPC_SUBPREFIX}\"`"
EOF
#else
#cat <<EOF >> ${OUTPUT_FILE}
#MPCROOT="${SCTK_PREFIX}/${MPC_TARGET}"
#EOF
#fi

cat <<EOF >> ${OUTPUT_FILE}
MPI_ROOT="\${MPCROOT}"
export MPI_ROOT

if test -z "\${PATH}" ; then
	PATH="\${MPCROOT}/bin"
	export PATH
else
	PATH="\${PATH}:\${MPCROOT}/bin"
	export PATH
fi

# if test -z "\${CPATH}" ; then
#    export CPATH="\${MPCROOT}/include"
# else
#    export CPATH="\${MPCROOT}/include:\${CPATH}"
# fi

if test -z "\${MANPATH}" ; then
	MANPATH="\${MPCROOT}/man"
	export MANPATH
else
	MANPATH="\${MPCROOT}/man:\${MANPATH}"
	export MANPATH
fi

if test -z "\${LIBRARY_PATH}" ; then
	LIBRARY_PATH="\${MPCROOT}/lib"
	export LIBRARY_PATH
else
	LIBRARY_PATH="\${MPCROOT}/lib:\${LIBRARY_PATH}"
	export LIBRARY_PATH
fi

EOF

if test "${ADD_TO_LIBRARY_PATH}" = "" ; then

cat <<EOF >> ${OUTPUT_FILE}
if test -z "\${LD_LIBRARY_PATH}" ; then
	LD_LIBRARY_PATH="\${MPCROOT}/lib"
	export LD_LIBRARY_PATH
else
	LD_LIBRARY_PATH="\${MPCROOT}/lib:\${LD_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
fi

if test -d "\${MPCROOT}/lib64" ; then
	LD_LIBRARY_PATH="\${MPCROOT}/lib64:\${LD_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
fi

if test -d "\${MPCROOT}/libsgcc" ; then
	LD_LIBRARY_PATH="\${MPCROOT}/libsgcc/lib:\${LD_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
fi
EOF

else
cat <<EOF >> ${OUTPUT_FILE}
if test -z "\${LD_LIBRARY_PATH}" ; then
	LD_LIBRARY_PATH="\${MPCROOT}/lib:${ADD_TO_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
else
	LD_LIBRARY_PATH="\${MPCROOT}/lib:${ADD_TO_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
fi

if test -d "\${MPCROOT}/lib64" ; then
	LD_LIBRARY_PATH="\${MPCROOT}/lib64:${ADD_TO_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
fi

if test -d "\${MPCROOT}/libsgcc" ; then
	LD_LIBRARY_PATH="\${MPCROOT}/libsgcc/lib:${ADD_TO_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
	export LD_LIBRARY_PATH
fi
EOF
fi

end_section


OUTPUT_FILE=bin/mpcvars.csh

begin_section Generate Environment Script ${OUTPUT_FILE}

# Header
echo "#!/bin/csh" > ${OUTPUT_FILE}
header_sh >> ${OUTPUT_FILE}

cat <<EOF >> ${OUTPUT_FILE}

set MPCROOT="`echo \\${MPC_RPREFIX}/${MPC_SUBPREFIX}`"
setenv MPI_ROOT "\${MPCROOT}"

if (\$?PATH) then
   setenv PATH "\${PATH}:\${MPCROOT}/bin"
else
   setenv PATH "\${MPCROOT}/bin"
endif

# if (\$?CPATH) then
#    setenv CPATH "\${MPCROOT}/include:\${CPATH}"
# else
#    setenv CPATH "\${MPCROOT}/include"
# endif

if (\$?MANPATH) then
  setenv MANPATH "\${MPCROOT}/man:\${MANPATH}"
else
  setenv MANPATH "\${MPCROOT}/man"
endif

if (\$?LIBRARY_PATH) then
   setenv LIBRARY_PATH "\${MPCROOT}/lib:\${LIBRARY_PATH}"
else
   setenv LIBRARY_PATH "\${MPCROOT}/lib"
endif

EOF

if test "${ADD_TO_LIBRARY_PATH}" = "" ; then

cat <<EOF >> ${OUTPUT_FILE}
if (\$?LD_LIBRARY_PATH) then
   setenv LD_LIBRARY_PATH "\${MPCROOT}/lib:\${LD_LIBRARY_PATH}"
else
   setenv LD_LIBRARY_PATH "\${MPCROOT}/lib"
endif

if ( -d "\${MPCROOT}/lib64" ) then
   setenv LD_LIBRARY_PATH "\${MPCROOT}/lib64:\${LD_LIBRARY_PATH}"
endif

if ( -d "\${MPCROOT}/libsgcc" ) then
	setenv LD_LIBRARY_PATH "\${MPCROOT}/libsgcc/lib:\${LD_LIBRARY_PATH}"
endif

EOF

else
cat <<EOF >> ${OUTPUT_FILE}
if (\$?LD_LIBRARY_PATH) then
   setenv LD_LIBRARY_PATH "\${MPCROOT}/lib:${ADD_TO_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
else
   setenv LD_LIBRARY_PATH "\${MPCROOT}/lib:${ADD_TO_LIBRARY_PATH}"
endif

if ( -d "\${MPCROOT}/lib64" ) then
   setenv LD_LIBRARY_PATH "\${MPCROOT}/lib64:${ADD_TO_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
endif

if ( -d "\${MPCROOT}/libsgcc" ) then
	setenv LD_LIBRARY_PATH "\${MPCROOT}/libsgcc/lib:${ADD_TO_LIBRARY_PATH}:\${LD_LIBRARY_PATH}"
endif

EOF
fi

end_section
