#!/bin/bash

# Hostname is generated by the mpc configure script
HOSTNAME=root@${SCTK_MIC_HOSTNAME}
WORKDIR_TARGET=/tmp/
WORKDIR_HOST=.
OUTPUT=$1.cross_output
LOG=/dev/null

# If a failure occurs
function fail {
  echo "ERROR: an error occured while running the cross_execution script"
  exit 1
}

# Copy from host to target
#echo "Running: scp $1 $HOSTNAME:$WORKDIR_TARGET || fail"
scp $1 $HOSTNAME:$WORKDIR_TARGET || fail
# Run binary
#echo "Running: ssh $HOSTNAME "$WORKDIR_TARGET/$1 > $WORKDIR_TARGET/$OUTPUT" || fail"
ssh $HOSTNAME "$WORKDIR_TARGET/$1 $2 > $WORKDIR_TARGET/$OUTPUT" || fail
# Copy from target to host
#echo "Running: scp $HOSTNAME:$WORKDIR_TARGET/$OUTPUT $WORKDIR_HOST || fail"
scp $HOSTNAME:$WORKDIR_TARGET/$OUTPUT $WORKDIR_HOST || fail

# Print the content of the file to stdout
cat $WORKDIR_HOST/$OUTPUT
rm $WORKDIR_HOST/$OUTPUT

exit 0
