! ############################# MPC License ############################## 
! # Wed Nov 19 15:19:19 CET 2008                                         # 
! # Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
! #                                                                      # 
! # IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
! # This file is part of the MPC Runtime.                                # 
! #                                                                      # 
! # This software is governed by the CeCILL-C license under French law   # 
! # and abiding by the rules of distribution of free software.  You can  # 
! # use, modify and/ or redistribute the software under the terms of     # 
! # the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
! # following URL http://www.cecill.info.                                # 
! #                                                                      # 
! # The fact that you are presently reading this means that you have     # 
! # had knowledge of the CeCILL-C license and that you accept its        # 
! # terms.                                                               # 
! #                                                                      # 
! # Authors:                                                             # 
! #   - BESNARD Jean-Baptiste jbbesnard@paratools.fr                     # 
! #   - AUTOGENERATED by genmod.py                                       # 
! #                                                                      # 
! ######################################################################## 

! /!\ DO NOT EDIT THIS FILE IS AUTOGENERATED BY modulegen.py

module mpi_f08_types

! If you want to extend this file, extend MPIf08_type.json

use,intrinsic :: iso_c_binding
use :: mpi_f08_ctypes
private :: c_Count, c_Status


type, bind(C) :: MPI_Comm
    integer :: val
end type MPI_Comm

type, bind(C) :: MPI_Session
    integer :: val
end type MPI_Session

type, bind(C) :: MPI_Datatype
    integer :: val
end type MPI_Datatype

type, bind(C) :: MPI_Errhandler
    integer :: val
end type MPI_Errhandler

type, bind(C) :: MPI_File
    integer :: val
end type MPI_File

type, bind(C) :: MPI_Group
    integer :: val
end type MPI_Group

type, bind(C) :: MPI_Info
    integer :: val
end type MPI_Info

type, bind(C) :: MPI_Request
    integer :: val
end type MPI_Request

type, bind(C) :: MPI_Win
    integer :: val
end type MPI_Win

type, bind(C) :: MPI_Message
    integer :: val
end type MPI_Message

type, bind(C) :: MPI_Op
    integer*8 :: val
end type MPI_Op

type, bind(C) :: MPI_Win_copy_attr_function
    type(c_ptr) :: val
end type MPI_Win_copy_attr_function

type, bind(C) :: MPI_Win_delete_attr_function
    type(c_ptr) :: val
end type MPI_Win_delete_attr_function

type, bind(C) :: MPI_Type_copy_attr_function
    type(c_ptr) :: val
end type MPI_Type_copy_attr_function

type, bind(C) :: MPI_Type_delete_attr_function
    type(c_ptr) :: val
end type MPI_Type_delete_attr_function

type, bind(C) :: MPI_Comm_copy_attr_function
    type(c_ptr) :: val
end type MPI_Comm_copy_attr_function

type, bind(C) :: MPI_Comm_delete_attr_function
    type(c_ptr) :: val
end type MPI_Comm_delete_attr_function

type, bind(C) :: MPI_Copy_function
    type(c_ptr) :: val
end type MPI_Copy_function

type, bind(C) :: MPI_Delete_function
    type(c_ptr) :: val
end type MPI_Delete_function

type, bind(C) :: MPI_Grequest_query_function
    type(c_ptr) :: val
end type MPI_Grequest_query_function

type, bind(C) :: MPI_Grequest_cancel_function
    type(c_ptr) :: val
end type MPI_Grequest_cancel_function

type, bind(C) :: MPI_Grequest_free_function
    type(c_ptr) :: val
end type MPI_Grequest_free_function

type, bind(C) :: MPI_Session_errhandler_function
    type(c_ptr) :: val
end type MPI_Session_errhandler_function

type, bind(C) :: MPI_Comm_errhandler_function
    type(c_ptr) :: val
end type MPI_Comm_errhandler_function

type, bind(C) :: MPI_Win_errhandler_function
    type(c_ptr) :: val
end type MPI_Win_errhandler_function

type, bind(C) :: MPI_Errhandler_function
    type(c_ptr) :: val
end type MPI_Errhandler_function

type, bind(C) :: MPI_File_errhandler_function
    type(c_ptr) :: val
end type MPI_File_errhandler_function

type, bind(C) :: MPI_Handler_function
    type(c_ptr) :: val
end type MPI_Handler_function

type, bind(C) :: MPI_User_function
    type(c_ptr) :: val
end type MPI_User_function

type, bind(C) :: MPI_Status
    integer :: MPI_SOURCE
    integer :: MPI_TAG
    integer :: MPI_ERROR
    integer :: cancelled
    integer*8 :: size
end type MPI_Status


interface operator(==)
   module procedure MPI_Comm_equal
   module procedure MPI_Comm_equal_c
   module procedure MPI_Comm_equal_cr
   module procedure MPI_Session_equal
   module procedure MPI_Session_equal_c
   module procedure MPI_Session_equal_cr
   module procedure MPI_Datatype_equal
   module procedure MPI_Datatype_equal_c
   module procedure MPI_Datatype_equal_cr
   module procedure MPI_Errhandler_equal
   module procedure MPI_Errhandler_equal_c
   module procedure MPI_Errhandler_equal_cr
   module procedure MPI_File_equal
   module procedure MPI_File_equal_c
   module procedure MPI_File_equal_cr
   module procedure MPI_Group_equal
   module procedure MPI_Group_equal_c
   module procedure MPI_Group_equal_cr
   module procedure MPI_Info_equal
   module procedure MPI_Info_equal_c
   module procedure MPI_Info_equal_cr
   module procedure MPI_Request_equal
   module procedure MPI_Request_equal_c
   module procedure MPI_Request_equal_cr
   module procedure MPI_Win_equal
   module procedure MPI_Win_equal_c
   module procedure MPI_Win_equal_cr
   module procedure MPI_Message_equal
   module procedure MPI_Message_equal_c
   module procedure MPI_Message_equal_cr
   module procedure MPI_Op_equal
   module procedure MPI_Op_equal_c
   module procedure MPI_Op_equal_cr
   module procedure MPI_Win_copy_attr_function_equal
   module procedure MPI_Win_delete_attr_function_equal
   module procedure MPI_Type_copy_attr_function_equal
   module procedure MPI_Type_delete_attr_function_equal
   module procedure MPI_Comm_copy_attr_function_equal
   module procedure MPI_Comm_delete_attr_function_equal
   module procedure MPI_Copy_function_equal
   module procedure MPI_Delete_function_equal
   module procedure MPI_Grequest_query_function_equal
   module procedure MPI_Grequest_cancel_function_equal
   module procedure MPI_Grequest_free_function_equal
   module procedure MPI_Session_errhandler_function_equal
   module procedure MPI_Comm_errhandler_function_equal
   module procedure MPI_Win_errhandler_function_equal
   module procedure MPI_Errhandler_function_equal
   module procedure MPI_File_errhandler_function_equal
   module procedure MPI_Handler_function_equal
   module procedure MPI_User_function_equal
   module procedure MPI_Status_equal
   module procedure MPI_Status_equal_c
   module procedure MPI_Status_equal_cr
end interface

private :: MPI_Comm_equal
private :: MPI_Comm_equal_c
private :: MPI_Session_equal
private :: MPI_Session_equal_c
private :: MPI_Datatype_equal
private :: MPI_Datatype_equal_c
private :: MPI_Errhandler_equal
private :: MPI_Errhandler_equal_c
private :: MPI_File_equal
private :: MPI_File_equal_c
private :: MPI_Group_equal
private :: MPI_Group_equal_c
private :: MPI_Info_equal
private :: MPI_Info_equal_c
private :: MPI_Request_equal
private :: MPI_Request_equal_c
private :: MPI_Win_equal
private :: MPI_Win_equal_c
private :: MPI_Message_equal
private :: MPI_Message_equal_c
private :: MPI_Op_equal
private :: MPI_Op_equal_c
private :: MPI_Win_copy_attr_function_equal
private :: MPI_Win_delete_attr_function_equal
private :: MPI_Type_copy_attr_function_equal
private :: MPI_Type_delete_attr_function_equal
private :: MPI_Comm_copy_attr_function_equal
private :: MPI_Comm_delete_attr_function_equal
private :: MPI_Copy_function_equal
private :: MPI_Delete_function_equal
private :: MPI_Grequest_query_function_equal
private :: MPI_Grequest_cancel_function_equal
private :: MPI_Grequest_free_function_equal
private :: MPI_Session_errhandler_function_equal
private :: MPI_Comm_errhandler_function_equal
private :: MPI_Win_errhandler_function_equal
private :: MPI_Errhandler_function_equal
private :: MPI_File_errhandler_function_equal
private :: MPI_Handler_function_equal
private :: MPI_User_function_equal
private :: MPI_Status_equal


interface operator(/=)
   module procedure MPI_Comm_notequal
   module procedure MPI_Comm_notequal_c
   module procedure MPI_Comm_notequal_cr
   module procedure MPI_Session_notequal
   module procedure MPI_Session_notequal_c
   module procedure MPI_Session_notequal_cr
   module procedure MPI_Datatype_notequal
   module procedure MPI_Datatype_notequal_c
   module procedure MPI_Datatype_notequal_cr
   module procedure MPI_Errhandler_notequal
   module procedure MPI_Errhandler_notequal_c
   module procedure MPI_Errhandler_notequal_cr
   module procedure MPI_File_notequal
   module procedure MPI_File_notequal_c
   module procedure MPI_File_notequal_cr
   module procedure MPI_Group_notequal
   module procedure MPI_Group_notequal_c
   module procedure MPI_Group_notequal_cr
   module procedure MPI_Info_notequal
   module procedure MPI_Info_notequal_c
   module procedure MPI_Info_notequal_cr
   module procedure MPI_Request_notequal
   module procedure MPI_Request_notequal_c
   module procedure MPI_Request_notequal_cr
   module procedure MPI_Win_notequal
   module procedure MPI_Win_notequal_c
   module procedure MPI_Win_notequal_cr
   module procedure MPI_Message_notequal
   module procedure MPI_Message_notequal_c
   module procedure MPI_Message_notequal_cr
   module procedure MPI_Op_notequal
   module procedure MPI_Op_notequal_c
   module procedure MPI_Op_notequal_cr
   module procedure MPI_Win_copy_attr_function_notequal
   module procedure MPI_Win_delete_attr_function_notequal
   module procedure MPI_Type_copy_attr_function_notequal
   module procedure MPI_Type_delete_attr_function_notequal
   module procedure MPI_Comm_copy_attr_function_notequal
   module procedure MPI_Comm_delete_attr_function_notequal
   module procedure MPI_Copy_function_notequal
   module procedure MPI_Delete_function_notequal
   module procedure MPI_Grequest_query_function_notequal
   module procedure MPI_Grequest_cancel_function_notequal
   module procedure MPI_Grequest_free_function_notequal
   module procedure MPI_Session_errhandler_function_notequal
   module procedure MPI_Comm_errhandler_function_notequal
   module procedure MPI_Win_errhandler_function_notequal
   module procedure MPI_Errhandler_function_notequal
   module procedure MPI_File_errhandler_function_notequal
   module procedure MPI_Handler_function_notequal
   module procedure MPI_User_function_notequal
   module procedure MPI_Status_notequal
   module procedure MPI_Status_notequal_c
   module procedure MPI_Status_notequal_cr
end interface

private :: MPI_Comm_notequal
private :: MPI_Comm_notequal_c
private :: MPI_Session_notequal
private :: MPI_Session_notequal_c
private :: MPI_Datatype_notequal
private :: MPI_Datatype_notequal_c
private :: MPI_Errhandler_notequal
private :: MPI_Errhandler_notequal_c
private :: MPI_File_notequal
private :: MPI_File_notequal_c
private :: MPI_Group_notequal
private :: MPI_Group_notequal_c
private :: MPI_Info_notequal
private :: MPI_Info_notequal_c
private :: MPI_Request_notequal
private :: MPI_Request_notequal_c
private :: MPI_Win_notequal
private :: MPI_Win_notequal_c
private :: MPI_Message_notequal
private :: MPI_Message_notequal_c
private :: MPI_Op_notequal
private :: MPI_Op_notequal_c
private :: MPI_Win_copy_attr_function_notequal
private :: MPI_Win_delete_attr_function_notequal
private :: MPI_Type_copy_attr_function_notequal
private :: MPI_Type_delete_attr_function_notequal
private :: MPI_Comm_copy_attr_function_notequal
private :: MPI_Comm_delete_attr_function_notequal
private :: MPI_Copy_function_notequal
private :: MPI_Delete_function_notequal
private :: MPI_Grequest_query_function_notequal
private :: MPI_Grequest_cancel_function_notequal
private :: MPI_Grequest_free_function_notequal
private :: MPI_Session_errhandler_function_notequal
private :: MPI_Comm_errhandler_function_notequal
private :: MPI_Win_errhandler_function_notequal
private :: MPI_Errhandler_function_notequal
private :: MPI_File_errhandler_function_notequal
private :: MPI_Handler_function_notequal
private :: MPI_User_function_notequal
private :: MPI_Status_notequal


interface assignment(=)
   module procedure MPI_Comm_assign
   module procedure MPI_Comm_assign_c
   module procedure MPI_Comm_assign_cr
   module procedure MPI_Session_assign
   module procedure MPI_Session_assign_c
   module procedure MPI_Session_assign_cr
   module procedure MPI_Datatype_assign
   module procedure MPI_Datatype_assign_c
   module procedure MPI_Datatype_assign_cr
   module procedure MPI_Errhandler_assign
   module procedure MPI_Errhandler_assign_c
   module procedure MPI_Errhandler_assign_cr
   module procedure MPI_File_assign
   module procedure MPI_File_assign_c
   module procedure MPI_File_assign_cr
   module procedure MPI_Group_assign
   module procedure MPI_Group_assign_c
   module procedure MPI_Group_assign_cr
   module procedure MPI_Info_assign
   module procedure MPI_Info_assign_c
   module procedure MPI_Info_assign_cr
   module procedure MPI_Request_assign
   module procedure MPI_Request_assign_c
   module procedure MPI_Request_assign_cr
   module procedure MPI_Win_assign
   module procedure MPI_Win_assign_c
   module procedure MPI_Win_assign_cr
   module procedure MPI_Message_assign
   module procedure MPI_Message_assign_c
   module procedure MPI_Message_assign_cr
   module procedure MPI_Op_assign
   module procedure MPI_Op_assign_c
   module procedure MPI_Op_assign_cr
   module procedure MPI_Win_copy_attr_function_assign
   module procedure MPI_Win_delete_attr_function_assign
   module procedure MPI_Type_copy_attr_function_assign
   module procedure MPI_Type_delete_attr_function_assign
   module procedure MPI_Comm_copy_attr_function_assign
   module procedure MPI_Comm_delete_attr_function_assign
   module procedure MPI_Copy_function_assign
   module procedure MPI_Delete_function_assign
   module procedure MPI_Grequest_query_function_assign
   module procedure MPI_Grequest_cancel_function_assign
   module procedure MPI_Grequest_free_function_assign
   module procedure MPI_Session_errhandler_function_assign
   module procedure MPI_Comm_errhandler_function_assign
   module procedure MPI_Win_errhandler_function_assign
   module procedure MPI_Errhandler_function_assign
   module procedure MPI_File_errhandler_function_assign
   module procedure MPI_Handler_function_assign
   module procedure MPI_User_function_assign
   module procedure MPI_Status_assign
   module procedure MPI_Status_assign_c
   module procedure MPI_Status_assign_cr
end interface

private :: MPI_Comm_assign
private :: MPI_Comm_assign_c
private :: MPI_Session_assign
private :: MPI_Session_assign_c
private :: MPI_Datatype_assign
private :: MPI_Datatype_assign_c
private :: MPI_Errhandler_assign
private :: MPI_Errhandler_assign_c
private :: MPI_File_assign
private :: MPI_File_assign_c
private :: MPI_Group_assign
private :: MPI_Group_assign_c
private :: MPI_Info_assign
private :: MPI_Info_assign_c
private :: MPI_Request_assign
private :: MPI_Request_assign_c
private :: MPI_Win_assign
private :: MPI_Win_assign_c
private :: MPI_Message_assign
private :: MPI_Message_assign_c
private :: MPI_Op_assign
private :: MPI_Op_assign_c
private :: MPI_Win_copy_attr_function_assign
private :: MPI_Win_delete_attr_function_assign
private :: MPI_Type_copy_attr_function_assign
private :: MPI_Type_delete_attr_function_assign
private :: MPI_Comm_copy_attr_function_assign
private :: MPI_Comm_delete_attr_function_assign
private :: MPI_Copy_function_assign
private :: MPI_Delete_function_assign
private :: MPI_Grequest_query_function_assign
private :: MPI_Grequest_cancel_function_assign
private :: MPI_Grequest_free_function_assign
private :: MPI_Session_errhandler_function_assign
private :: MPI_Comm_errhandler_function_assign
private :: MPI_Win_errhandler_function_assign
private :: MPI_Errhandler_function_assign
private :: MPI_File_errhandler_function_assign
private :: MPI_Handler_function_assign
private :: MPI_User_function_assign
private :: MPI_Status_assign


contains

function MPI_Comm_equal( a , b) result(r)
   type(MPI_Comm), intent(in) ::  a
   type(MPI_Comm), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Comm_equal

function MPI_Comm_equal_c( a , b) result(r)
   type(MPI_Comm), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Comm_equal_c

function MPI_Comm_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Comm), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Comm_equal_cr

function MPI_Comm_notequal( a , b) result(r)
   type(MPI_Comm), intent(in) ::  a
   type(MPI_Comm), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Comm_notequal

function MPI_Comm_notequal_c( a , b) result(r)
   type(MPI_Comm), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Comm_notequal_c

function MPI_Comm_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Comm), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Comm_notequal_cr

subroutine MPI_Comm_assign( a , b)
   type(MPI_Comm), intent(out) ::  a
   type(MPI_Comm), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Comm_assign

subroutine MPI_Comm_assign_c( a , b)
   type(MPI_Comm), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Comm_assign_c

subroutine MPI_Comm_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Comm), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Comm_assign_cr

function MPI_Session_equal( a , b) result(r)
   type(MPI_Session), intent(in) ::  a
   type(MPI_Session), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Session_equal

function MPI_Session_equal_c( a , b) result(r)
   type(MPI_Session), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Session_equal_c

function MPI_Session_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Session), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Session_equal_cr

function MPI_Session_notequal( a , b) result(r)
   type(MPI_Session), intent(in) ::  a
   type(MPI_Session), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Session_notequal

function MPI_Session_notequal_c( a , b) result(r)
   type(MPI_Session), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Session_notequal_c

function MPI_Session_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Session), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Session_notequal_cr

subroutine MPI_Session_assign( a , b)
   type(MPI_Session), intent(out) ::  a
   type(MPI_Session), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Session_assign

subroutine MPI_Session_assign_c( a , b)
   type(MPI_Session), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Session_assign_c

subroutine MPI_Session_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Session), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Session_assign_cr

function MPI_Datatype_equal( a , b) result(r)
   type(MPI_Datatype), intent(in) ::  a
   type(MPI_Datatype), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Datatype_equal

function MPI_Datatype_equal_c( a , b) result(r)
   type(MPI_Datatype), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Datatype_equal_c

function MPI_Datatype_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Datatype), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Datatype_equal_cr

function MPI_Datatype_notequal( a , b) result(r)
   type(MPI_Datatype), intent(in) ::  a
   type(MPI_Datatype), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Datatype_notequal

function MPI_Datatype_notequal_c( a , b) result(r)
   type(MPI_Datatype), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Datatype_notequal_c

function MPI_Datatype_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Datatype), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Datatype_notequal_cr

subroutine MPI_Datatype_assign( a , b)
   type(MPI_Datatype), intent(out) ::  a
   type(MPI_Datatype), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Datatype_assign

subroutine MPI_Datatype_assign_c( a , b)
   type(MPI_Datatype), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Datatype_assign_c

subroutine MPI_Datatype_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Datatype), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Datatype_assign_cr

function MPI_Errhandler_equal( a , b) result(r)
   type(MPI_Errhandler), intent(in) ::  a
   type(MPI_Errhandler), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Errhandler_equal

function MPI_Errhandler_equal_c( a , b) result(r)
   type(MPI_Errhandler), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Errhandler_equal_c

function MPI_Errhandler_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Errhandler), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Errhandler_equal_cr

function MPI_Errhandler_notequal( a , b) result(r)
   type(MPI_Errhandler), intent(in) ::  a
   type(MPI_Errhandler), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Errhandler_notequal

function MPI_Errhandler_notequal_c( a , b) result(r)
   type(MPI_Errhandler), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Errhandler_notequal_c

function MPI_Errhandler_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Errhandler), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Errhandler_notequal_cr

subroutine MPI_Errhandler_assign( a , b)
   type(MPI_Errhandler), intent(out) ::  a
   type(MPI_Errhandler), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Errhandler_assign

subroutine MPI_Errhandler_assign_c( a , b)
   type(MPI_Errhandler), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Errhandler_assign_c

subroutine MPI_Errhandler_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Errhandler), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Errhandler_assign_cr

function MPI_File_equal( a , b) result(r)
   type(MPI_File), intent(in) ::  a
   type(MPI_File), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_File_equal

function MPI_File_equal_c( a , b) result(r)
   type(MPI_File), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_File_equal_c

function MPI_File_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_File), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_File_equal_cr

function MPI_File_notequal( a , b) result(r)
   type(MPI_File), intent(in) ::  a
   type(MPI_File), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_File_notequal

function MPI_File_notequal_c( a , b) result(r)
   type(MPI_File), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_File_notequal_c

function MPI_File_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_File), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_File_notequal_cr

subroutine MPI_File_assign( a , b)
   type(MPI_File), intent(out) ::  a
   type(MPI_File), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_File_assign

subroutine MPI_File_assign_c( a , b)
   type(MPI_File), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_File_assign_c

subroutine MPI_File_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_File), intent(in) ::  b 
   a =  b%val
end subroutine MPI_File_assign_cr

function MPI_Group_equal( a , b) result(r)
   type(MPI_Group), intent(in) ::  a
   type(MPI_Group), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Group_equal

function MPI_Group_equal_c( a , b) result(r)
   type(MPI_Group), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Group_equal_c

function MPI_Group_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Group), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Group_equal_cr

function MPI_Group_notequal( a , b) result(r)
   type(MPI_Group), intent(in) ::  a
   type(MPI_Group), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Group_notequal

function MPI_Group_notequal_c( a , b) result(r)
   type(MPI_Group), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Group_notequal_c

function MPI_Group_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Group), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Group_notequal_cr

subroutine MPI_Group_assign( a , b)
   type(MPI_Group), intent(out) ::  a
   type(MPI_Group), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Group_assign

subroutine MPI_Group_assign_c( a , b)
   type(MPI_Group), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Group_assign_c

subroutine MPI_Group_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Group), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Group_assign_cr

function MPI_Info_equal( a , b) result(r)
   type(MPI_Info), intent(in) ::  a
   type(MPI_Info), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Info_equal

function MPI_Info_equal_c( a , b) result(r)
   type(MPI_Info), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Info_equal_c

function MPI_Info_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Info), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Info_equal_cr

function MPI_Info_notequal( a , b) result(r)
   type(MPI_Info), intent(in) ::  a
   type(MPI_Info), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Info_notequal

function MPI_Info_notequal_c( a , b) result(r)
   type(MPI_Info), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Info_notequal_c

function MPI_Info_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Info), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Info_notequal_cr

subroutine MPI_Info_assign( a , b)
   type(MPI_Info), intent(out) ::  a
   type(MPI_Info), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Info_assign

subroutine MPI_Info_assign_c( a , b)
   type(MPI_Info), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Info_assign_c

subroutine MPI_Info_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Info), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Info_assign_cr

function MPI_Request_equal( a , b) result(r)
   type(MPI_Request), intent(in) ::  a
   type(MPI_Request), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Request_equal

function MPI_Request_equal_c( a , b) result(r)
   type(MPI_Request), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Request_equal_c

function MPI_Request_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Request), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Request_equal_cr

function MPI_Request_notequal( a , b) result(r)
   type(MPI_Request), intent(in) ::  a
   type(MPI_Request), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Request_notequal

function MPI_Request_notequal_c( a , b) result(r)
   type(MPI_Request), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Request_notequal_c

function MPI_Request_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Request), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Request_notequal_cr

subroutine MPI_Request_assign( a , b)
   type(MPI_Request), intent(out) ::  a
   type(MPI_Request), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Request_assign

subroutine MPI_Request_assign_c( a , b)
   type(MPI_Request), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Request_assign_c

subroutine MPI_Request_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Request), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Request_assign_cr

function MPI_Win_equal( a , b) result(r)
   type(MPI_Win), intent(in) ::  a
   type(MPI_Win), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Win_equal

function MPI_Win_equal_c( a , b) result(r)
   type(MPI_Win), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Win_equal_c

function MPI_Win_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Win), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Win_equal_cr

function MPI_Win_notequal( a , b) result(r)
   type(MPI_Win), intent(in) ::  a
   type(MPI_Win), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Win_notequal

function MPI_Win_notequal_c( a , b) result(r)
   type(MPI_Win), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Win_notequal_c

function MPI_Win_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Win), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Win_notequal_cr

subroutine MPI_Win_assign( a , b)
   type(MPI_Win), intent(out) ::  a
   type(MPI_Win), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Win_assign

subroutine MPI_Win_assign_c( a , b)
   type(MPI_Win), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Win_assign_c

subroutine MPI_Win_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Win), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Win_assign_cr

function MPI_Message_equal( a , b) result(r)
   type(MPI_Message), intent(in) ::  a
   type(MPI_Message), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Message_equal

function MPI_Message_equal_c( a , b) result(r)
   type(MPI_Message), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Message_equal_c

function MPI_Message_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Message), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Message_equal_cr

function MPI_Message_notequal( a , b) result(r)
   type(MPI_Message), intent(in) ::  a
   type(MPI_Message), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Message_notequal

function MPI_Message_notequal_c( a , b) result(r)
   type(MPI_Message), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Message_notequal_c

function MPI_Message_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Message), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Message_notequal_cr

subroutine MPI_Message_assign( a , b)
   type(MPI_Message), intent(out) ::  a
   type(MPI_Message), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Message_assign

subroutine MPI_Message_assign_c( a , b)
   type(MPI_Message), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Message_assign_c

subroutine MPI_Message_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Message), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Message_assign_cr

function MPI_Op_equal( a , b) result(r)
   type(MPI_Op), intent(in) ::  a
   type(MPI_Op), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b%val  )&
 )
end function MPI_Op_equal

function MPI_Op_equal_c( a , b) result(r)
   type(MPI_Op), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%val ==  b  )&
 )
end function MPI_Op_equal_c

function MPI_Op_equal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Op), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a ==  b%val )&
 )
end function MPI_Op_equal_cr

function MPI_Op_notequal( a , b) result(r)
   type(MPI_Op), intent(in) ::  a
   type(MPI_Op), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b%val  )&
 )
end function MPI_Op_notequal

function MPI_Op_notequal_c( a , b) result(r)
   type(MPI_Op), intent(in) ::  a 
   integer(c_int), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%val /=  b  )&
 )
end function MPI_Op_notequal_c

function MPI_Op_notequal_cr( a , b) result(r)
   integer(c_int), intent(in) ::  a 
   type(MPI_Op), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a /=  b%val )&
 )
end function MPI_Op_notequal_cr

subroutine MPI_Op_assign( a , b)
   type(MPI_Op), intent(out) ::  a
   type(MPI_Op), intent(in) ::  b
   a%val =  b%val
end subroutine MPI_Op_assign

subroutine MPI_Op_assign_c( a , b)
   type(MPI_Op), intent(out) ::  a 
   integer(c_int), intent(in) ::  b 
   a%val =  b
end subroutine MPI_Op_assign_c

subroutine MPI_Op_assign_cr( a , b)
   integer(c_int), intent(out) ::  a 
   type(MPI_Op), intent(in) ::  b 
   a =  b%val
end subroutine MPI_Op_assign_cr

function MPI_Win_copy_attr_function_equal( a , b) result(r)
   type(MPI_Win_copy_attr_function), intent(in) ::  a
   type(MPI_Win_copy_attr_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Win_copy_attr_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Win_copy_attr_function_notequal( a , b) result(r)
   type(MPI_Win_copy_attr_function), intent(in) ::  a
   type(MPI_Win_copy_attr_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Win_copy_attr_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Win_copy_attr_function_assign( a , b)
   type(MPI_Win_copy_attr_function), intent(out) ::  a
   type(MPI_Win_copy_attr_function), intent(in) ::  b
end subroutine MPI_Win_copy_attr_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Win_delete_attr_function_equal( a , b) result(r)
   type(MPI_Win_delete_attr_function), intent(in) ::  a
   type(MPI_Win_delete_attr_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Win_delete_attr_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Win_delete_attr_function_notequal( a , b) result(r)
   type(MPI_Win_delete_attr_function), intent(in) ::  a
   type(MPI_Win_delete_attr_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Win_delete_attr_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Win_delete_attr_function_assign( a , b)
   type(MPI_Win_delete_attr_function), intent(out) ::  a
   type(MPI_Win_delete_attr_function), intent(in) ::  b
end subroutine MPI_Win_delete_attr_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Type_copy_attr_function_equal( a , b) result(r)
   type(MPI_Type_copy_attr_function), intent(in) ::  a
   type(MPI_Type_copy_attr_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Type_copy_attr_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Type_copy_attr_function_notequal( a , b) result(r)
   type(MPI_Type_copy_attr_function), intent(in) ::  a
   type(MPI_Type_copy_attr_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Type_copy_attr_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Type_copy_attr_function_assign( a , b)
   type(MPI_Type_copy_attr_function), intent(out) ::  a
   type(MPI_Type_copy_attr_function), intent(in) ::  b
end subroutine MPI_Type_copy_attr_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Type_delete_attr_function_equal( a , b) result(r)
   type(MPI_Type_delete_attr_function), intent(in) ::  a
   type(MPI_Type_delete_attr_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Type_delete_attr_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Type_delete_attr_function_notequal( a , b) result(r)
   type(MPI_Type_delete_attr_function), intent(in) ::  a
   type(MPI_Type_delete_attr_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Type_delete_attr_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Type_delete_attr_function_assign( a , b)
   type(MPI_Type_delete_attr_function), intent(out) ::  a
   type(MPI_Type_delete_attr_function), intent(in) ::  b
end subroutine MPI_Type_delete_attr_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Comm_copy_attr_function_equal( a , b) result(r)
   type(MPI_Comm_copy_attr_function), intent(in) ::  a
   type(MPI_Comm_copy_attr_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Comm_copy_attr_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Comm_copy_attr_function_notequal( a , b) result(r)
   type(MPI_Comm_copy_attr_function), intent(in) ::  a
   type(MPI_Comm_copy_attr_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Comm_copy_attr_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Comm_copy_attr_function_assign( a , b)
   type(MPI_Comm_copy_attr_function), intent(out) ::  a
   type(MPI_Comm_copy_attr_function), intent(in) ::  b
end subroutine MPI_Comm_copy_attr_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Comm_delete_attr_function_equal( a , b) result(r)
   type(MPI_Comm_delete_attr_function), intent(in) ::  a
   type(MPI_Comm_delete_attr_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Comm_delete_attr_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Comm_delete_attr_function_notequal( a , b) result(r)
   type(MPI_Comm_delete_attr_function), intent(in) ::  a
   type(MPI_Comm_delete_attr_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Comm_delete_attr_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Comm_delete_attr_function_assign( a , b)
   type(MPI_Comm_delete_attr_function), intent(out) ::  a
   type(MPI_Comm_delete_attr_function), intent(in) ::  b
end subroutine MPI_Comm_delete_attr_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Copy_function_equal( a , b) result(r)
   type(MPI_Copy_function), intent(in) ::  a
   type(MPI_Copy_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Copy_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Copy_function_notequal( a , b) result(r)
   type(MPI_Copy_function), intent(in) ::  a
   type(MPI_Copy_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Copy_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Copy_function_assign( a , b)
   type(MPI_Copy_function), intent(out) ::  a
   type(MPI_Copy_function), intent(in) ::  b
end subroutine MPI_Copy_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Delete_function_equal( a , b) result(r)
   type(MPI_Delete_function), intent(in) ::  a
   type(MPI_Delete_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Delete_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Delete_function_notequal( a , b) result(r)
   type(MPI_Delete_function), intent(in) ::  a
   type(MPI_Delete_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Delete_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Delete_function_assign( a , b)
   type(MPI_Delete_function), intent(out) ::  a
   type(MPI_Delete_function), intent(in) ::  b
end subroutine MPI_Delete_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Grequest_query_function_equal( a , b) result(r)
   type(MPI_Grequest_query_function), intent(in) ::  a
   type(MPI_Grequest_query_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Grequest_query_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Grequest_query_function_notequal( a , b) result(r)
   type(MPI_Grequest_query_function), intent(in) ::  a
   type(MPI_Grequest_query_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Grequest_query_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Grequest_query_function_assign( a , b)
   type(MPI_Grequest_query_function), intent(out) ::  a
   type(MPI_Grequest_query_function), intent(in) ::  b
end subroutine MPI_Grequest_query_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Grequest_cancel_function_equal( a , b) result(r)
   type(MPI_Grequest_cancel_function), intent(in) ::  a
   type(MPI_Grequest_cancel_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Grequest_cancel_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Grequest_cancel_function_notequal( a , b) result(r)
   type(MPI_Grequest_cancel_function), intent(in) ::  a
   type(MPI_Grequest_cancel_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Grequest_cancel_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Grequest_cancel_function_assign( a , b)
   type(MPI_Grequest_cancel_function), intent(out) ::  a
   type(MPI_Grequest_cancel_function), intent(in) ::  b
end subroutine MPI_Grequest_cancel_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Grequest_free_function_equal( a , b) result(r)
   type(MPI_Grequest_free_function), intent(in) ::  a
   type(MPI_Grequest_free_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Grequest_free_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Grequest_free_function_notequal( a , b) result(r)
   type(MPI_Grequest_free_function), intent(in) ::  a
   type(MPI_Grequest_free_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Grequest_free_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Grequest_free_function_assign( a , b)
   type(MPI_Grequest_free_function), intent(out) ::  a
   type(MPI_Grequest_free_function), intent(in) ::  b
end subroutine MPI_Grequest_free_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Session_errhandler_function_equal( a , b) result(r)
   type(MPI_Session_errhandler_function), intent(in) ::  a
   type(MPI_Session_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Session_errhandler_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Session_errhandler_function_notequal( a , b) result(r)
   type(MPI_Session_errhandler_function), intent(in) ::  a
   type(MPI_Session_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Session_errhandler_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Session_errhandler_function_assign( a , b)
   type(MPI_Session_errhandler_function), intent(out) ::  a
   type(MPI_Session_errhandler_function), intent(in) ::  b
end subroutine MPI_Session_errhandler_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Comm_errhandler_function_equal( a , b) result(r)
   type(MPI_Comm_errhandler_function), intent(in) ::  a
   type(MPI_Comm_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Comm_errhandler_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Comm_errhandler_function_notequal( a , b) result(r)
   type(MPI_Comm_errhandler_function), intent(in) ::  a
   type(MPI_Comm_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Comm_errhandler_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Comm_errhandler_function_assign( a , b)
   type(MPI_Comm_errhandler_function), intent(out) ::  a
   type(MPI_Comm_errhandler_function), intent(in) ::  b
end subroutine MPI_Comm_errhandler_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Win_errhandler_function_equal( a , b) result(r)
   type(MPI_Win_errhandler_function), intent(in) ::  a
   type(MPI_Win_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Win_errhandler_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Win_errhandler_function_notequal( a , b) result(r)
   type(MPI_Win_errhandler_function), intent(in) ::  a
   type(MPI_Win_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Win_errhandler_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Win_errhandler_function_assign( a , b)
   type(MPI_Win_errhandler_function), intent(out) ::  a
   type(MPI_Win_errhandler_function), intent(in) ::  b
end subroutine MPI_Win_errhandler_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Errhandler_function_equal( a , b) result(r)
   type(MPI_Errhandler_function), intent(in) ::  a
   type(MPI_Errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Errhandler_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Errhandler_function_notequal( a , b) result(r)
   type(MPI_Errhandler_function), intent(in) ::  a
   type(MPI_Errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Errhandler_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Errhandler_function_assign( a , b)
   type(MPI_Errhandler_function), intent(out) ::  a
   type(MPI_Errhandler_function), intent(in) ::  b
end subroutine MPI_Errhandler_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_File_errhandler_function_equal( a , b) result(r)
   type(MPI_File_errhandler_function), intent(in) ::  a
   type(MPI_File_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_File_errhandler_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_File_errhandler_function_notequal( a , b) result(r)
   type(MPI_File_errhandler_function), intent(in) ::  a
   type(MPI_File_errhandler_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_File_errhandler_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_File_errhandler_function_assign( a , b)
   type(MPI_File_errhandler_function), intent(out) ::  a
   type(MPI_File_errhandler_function), intent(in) ::  b
end subroutine MPI_File_errhandler_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Handler_function_equal( a , b) result(r)
   type(MPI_Handler_function), intent(in) ::  a
   type(MPI_Handler_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_Handler_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_Handler_function_notequal( a , b) result(r)
   type(MPI_Handler_function), intent(in) ::  a
   type(MPI_Handler_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_Handler_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_Handler_function_assign( a , b)
   type(MPI_Handler_function), intent(out) ::  a
   type(MPI_Handler_function), intent(in) ::  b
end subroutine MPI_Handler_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_User_function_equal( a , b) result(r)
   type(MPI_User_function), intent(in) ::  a
   type(MPI_User_function), intent(in) ::  b
   logical :: r
   r = ( .TRUE. )
end function MPI_User_function_equal

!SKIP function ptr
!SKIP function ptr
function MPI_User_function_notequal( a , b) result(r)
   type(MPI_User_function), intent(in) ::  a
   type(MPI_User_function), intent(in) ::  b
   logical :: r
   r = ( .FALSE. )
end function MPI_User_function_notequal

!SKIP function ptr
!SKIP function ptr
subroutine MPI_User_function_assign( a , b)
   type(MPI_User_function), intent(out) ::  a
   type(MPI_User_function), intent(in) ::  b
end subroutine MPI_User_function_assign

!SKIP function ptr
!SKIP function ptr
function MPI_Status_equal( a , b) result(r)
   type(MPI_Status), intent(in) ::  a
   type(MPI_Status), intent(in) ::  b
   logical :: r
   r = ( .TRUE.  .AND. ( a%MPI_SOURCE ==  b%MPI_SOURCE  )&
  .AND. ( a%MPI_TAG ==  b%MPI_TAG  )&
  .AND. ( a%MPI_ERROR ==  b%MPI_ERROR  )&
  .AND. ( a%cancelled ==  b%cancelled  )&
  .AND. ( a%size ==  b%size  )&
 )
end function MPI_Status_equal

function MPI_Status_equal_c( a , b) result(r)
   type(MPI_Status), intent(in) ::  a 
   type(c_Status), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%MPI_SOURCE ==  b%MPI_SOURCE  )&
  .AND. ( a%MPI_TAG ==  b%MPI_TAG  )&
  .AND. ( a%MPI_ERROR ==  b%MPI_ERROR  )&
  .AND. ( a%cancelled ==  b%cancelled  )&
  .AND. ( a%size ==  b%size  )&
 )
end function MPI_Status_equal_c

function MPI_Status_equal_cr( a , b) result(r)
   type(c_Status), intent(in) ::  a 
   type(MPI_Status), intent(in) ::  b 
   logical :: r
   r = ( .TRUE.  .AND. ( a%MPI_SOURCE ==  b%MPI_SOURCE  )&
  .AND. ( a%MPI_TAG ==  b%MPI_TAG  )&
  .AND. ( a%MPI_ERROR ==  b%MPI_ERROR  )&
  .AND. ( a%cancelled ==  b%cancelled  )&
  .AND. ( a%size ==  b%size  )&
 )
end function MPI_Status_equal_cr

function MPI_Status_notequal( a , b) result(r)
   type(MPI_Status), intent(in) ::  a
   type(MPI_Status), intent(in) ::  b
   logical :: r
   r = ( .FALSE.  .OR. ( a%MPI_SOURCE /=  b%MPI_SOURCE  )&
  .OR. ( a%MPI_TAG /=  b%MPI_TAG  )&
  .OR. ( a%MPI_ERROR /=  b%MPI_ERROR  )&
  .OR. ( a%cancelled /=  b%cancelled  )&
  .OR. ( a%size /=  b%size  )&
 )
end function MPI_Status_notequal

function MPI_Status_notequal_c( a , b) result(r)
   type(MPI_Status), intent(in) ::  a 
   type(c_Status), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%MPI_SOURCE /=  b%MPI_SOURCE  )&
  .OR. ( a%MPI_TAG /=  b%MPI_TAG  )&
  .OR. ( a%MPI_ERROR /=  b%MPI_ERROR  )&
  .OR. ( a%cancelled /=  b%cancelled  )&
  .OR. ( a%size /=  b%size  )&
 )
end function MPI_Status_notequal_c

function MPI_Status_notequal_cr( a , b) result(r)
   type(c_Status), intent(in) ::  a 
   type(MPI_Status), intent(in) ::  b 
   logical :: r
   r = ( .FALSE.  .OR. ( a%MPI_SOURCE /=  b%MPI_SOURCE  )&
  .OR. ( a%MPI_TAG /=  b%MPI_TAG  )&
  .OR. ( a%MPI_ERROR /=  b%MPI_ERROR  )&
  .OR. ( a%cancelled /=  b%cancelled  )&
  .OR. ( a%size /=  b%size  )&
 )
end function MPI_Status_notequal_cr

subroutine MPI_Status_assign( a , b)
   type(MPI_Status), intent(out) ::  a
   type(MPI_Status), intent(in) ::  b
   a%MPI_SOURCE =  b%MPI_SOURCE
   a%MPI_TAG =  b%MPI_TAG
   a%MPI_ERROR =  b%MPI_ERROR
   a%cancelled =  b%cancelled
   a%size =  b%size
end subroutine MPI_Status_assign

subroutine MPI_Status_assign_c( a , b)
   type(MPI_Status), intent(out) ::  a 
   type(c_Status), intent(in) ::  b 
   a%MPI_SOURCE =  b%MPI_SOURCE
   a%MPI_TAG =  b%MPI_TAG
   a%MPI_ERROR =  b%MPI_ERROR
   a%cancelled =  b%cancelled
   a%size =  b%size
end subroutine MPI_Status_assign_c

subroutine MPI_Status_assign_cr( a , b)
   type(c_Status), intent(out) ::  a 
   type(MPI_Status), intent(in) ::  b 
   a%MPI_SOURCE =  b%MPI_SOURCE
   a%MPI_TAG =  b%MPI_TAG
   a%MPI_ERROR =  b%MPI_ERROR
   a%cancelled =  b%cancelled
   a%size =  b%size
end subroutine MPI_Status_assign_cr



end module mpi_f08_types
