! ############################# MPC License ############################## 
! # Wed Nov 19 15:19:19 CET 2008                                         # 
! # Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
! #                                                                      # 
! # IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
! # This file is part of the MPC Runtime.                                # 
! #                                                                      # 
! # This software is governed by the CeCILL-C license under French law   # 
! # and abiding by the rules of distribution of free software.  You can  # 
! # use, modify and/ or redistribute the software under the terms of     # 
! # the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
! # following URL http://www.cecill.info.                                # 
! #                                                                      # 
! # The fact that you are presently reading this means that you have     # 
! # had knowledge of the CeCILL-C license and that you accept its        # 
! # terms.                                                               # 
! #                                                                      # 
! # Authors:                                                             # 
! #   - BESNARD Jean-Baptiste jbbesnard@paratools.fr                     # 
! #   - AUTOGENERATED by genmod.py                                       # 
! #                                                                      # 
! ######################################################################## 

! /!\ DO NOT EDIT THIS FILE IS AUTOGENERATED BY modulegen.py

module mpi_f08_ctypes

! If you want to extend this file, extend MPIf08_ctype.json

use,intrinsic :: iso_c_binding


integer, parameter :: c_Offset = c_intptr_t
integer, parameter :: c_Group = c_int
integer, parameter :: c_Errhandler = c_int
integer, parameter :: c_Message = c_int
integer, parameter :: c_Count = c_intptr_t
integer, parameter :: int = c_int
integer, parameter :: c_Op = c_int
integer, parameter :: c_Datatype = c_int
integer, parameter :: c_Aint = c_intptr_t
integer, parameter :: bool = c_int
integer, parameter :: c_File = c_int
integer, parameter :: c_Comm = c_int
integer, parameter :: c_Win = c_int
integer, parameter :: c_Request = c_int
integer, parameter :: c_Info = c_int

!If you ever need to change this STATUS edit genmod.py
type, bind(c) :: c_Status
   integer(c_int)  :: MPI_SOURCE
   integer(c_int)  :: MPI_TAG
   integer(c_int)  :: MPI_ERROR
   integer(c_int)  :: cancelled
   integer(c_intptr_t)  :: size
end type c_Status

end module mpi_f08_ctypes
