#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - CARRIBAULT Patrick patrick.carribault@cea.fr                     #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#   - JAEGER Julien julien.jaeger@cea.fr                               #
#                                                                      #
########################################################################
RED="`printf "\033[1;31m"`"
GRE="`printf "\033[1;32m"`"
DEF="`printf "\033[0;0m"`"

print_error()
{
	printf "${RED}ERROR: ${1}\n${DEF}"
}

safe_exec()
{
	text="${1}"; shift
	comm="$@"
	${comm}
	if test "$?" != "0";
	then
		print_error "${comm} failed ! Abort"
		exit 1
	fi
	printf "${GRE}${text} : OK${DEF}\n"

}

CURRENT_PATH="`dirname $0`"

MPC_SOURCE_DIRECTORY="${CURRENT_PATH}/../"

export MPC_SOURCE_DIRECTORY

if test -z "`which doxygen 2> /dev/null`";
then
	print_error "Unable to find a valid Doxygen installation (which doxygen)"
	print_error "Please install it and re-run."
	exit 1
fi

safe_exec "Generating Documentation into ${MPC_SOURCE_DIRECTORY}/doc/build/" doxygen ${MPC_SOURCE_DIRECTORY}/doc/Doxyfile.in
