#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - CARRIBAULT Patrick patrick.carribault@cea.fr                     #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#   - JAEGER Julien julien.jaeger@cea.fr                               #
#                                                                      #
########################################################################
RED="$(printf "\033[1;31m")"
GRE="$(printf "\033[1;32m")"
DEF="$(printf "\033[0;0m")"

verbose=0

print_error() {
	printf "${RED}ERROR: ${1}\n${DEF}"
}

safe_exec() {
	local text="${1}"
	shift
	comm="$@"
	printf "${text}..."

	if [ $verbose -eq 1 ]; then
		${comm}
	else
		${comm} 1>/dev/null 2>/dev/null
	fi

	if test "$?" != "0"; then
		print_error "\r${comm} failed ! Abort"
		exit 1
	fi
	printf "\r${GRE}${text} : OK${DEF}\n"

}

if [ $# -gt 1 ]; then
	print_error "Usage: $0 [-v]"
	exit 2
elif [ $# -eq 1 ]; then
	if [ $1 == "-v" ]; then
		verbose=1
	else
		print_error "Usage: $0 [-v]"
		exit 2
	fi
fi

CURRENT_PATH="$(dirname $0)"

MPC_DOC_DIRECTORY="${CURRENT_PATH}/"
MPC_SOURCE_DIRECTORY="${CURRENT_PATH}/../"

export MPC_DOC_DIRECTORY
export MPC_SOURCE_DIRECTORY

safe_exec "Create buildir" mkdir -p ${MPC_DOC_DIRECTORY}build/doxygen ${MPC_DOC_DIRECTORY}build/sphinx
if test -z "$(which doxygen 2>/dev/null)"; then
	print_error "Skipping Doxygen: not found IN PATH"
	print_error "Please install it and re-run."
	exit 10
else
	safe_exec "Generating doxygen" doxygen ${MPC_DOC_DIRECTORY}Doxyfile.in
fi

if test -z "$(which sphinx-build 2>/dev/null)"; then
	print_error "Skipping RTD-compliant Sphinx Documentation: sphinx-build not found in PATH"
	print_error "Please install it and re-run."
	exit 11
else
	safe_exec "Generating RTD-compliant Sphinx" make -f ${MPC_DOC_DIRECTORY}Makefile.sphinx html
fi
printf "${GRE}Documentation generated under ${MPC_DOC_DIRECTORY}build/sphinx${DEF}\n"
