! ############################# MPC License ############################## 
! # Wed Nov 19 15:19:19 CET 2008                                         # 
! # Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
! #                                                                      # 
! # IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
! # This file is part of the MPC Runtime.                                # 
! #                                                                      # 
! # This software is governed by the CeCILL-C license under French law   # 
! # and abiding by the rules of distribution of free software.  You can  # 
! # use, modify and/ or redistribute the software under the terms of     # 
! # the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
! # following URL http://www.cecill.info.                                # 
! #                                                                      # 
! # The fact that you are presently reading this means that you have     # 
! # had knowledge of the CeCILL-C license and that you accept its        # 
! # terms.                                                               # 
! #                                                                      # 
! # Authors:                                                             # 
! #   - PERACHE Marc marc.perache@cea.fr                                 # 
! #                                                                      # 
! ######################################################################## 
       INTEGER MPI_THREAD_SINGLE
       PARAMETER (MPI_THREAD_SINGLE=0)
       INTEGER MPI_THREAD_FUNNELED
       PARAMETER (MPI_THREAD_FUNNELED=1)
       INTEGER MPI_THREAD_SERIALIZED
       PARAMETER (MPI_THREAD_SERIALIZED=2)
       INTEGER MPI_THREAD_MULTIPLE
       PARAMETER (MPI_THREAD_MULTIPLE=3)
       INTEGER MPI_COMM_WORLD
       PARAMETER (MPI_COMM_WORLD=0)
       INTEGER MPI_COMM_SELF
       PARAMETER (MPI_COMM_SELF=1)
       INTEGER MPI_SUCCESS
       PARAMETER (MPI_SUCCESS=0)
       INTEGER MPI_ERR_BUFFER
       PARAMETER (MPI_ERR_BUFFER=1)
       INTEGER MPI_ERR_COUNT
       PARAMETER (MPI_ERR_COUNT=2)
       INTEGER MPI_ERR_TYPE
       PARAMETER (MPI_ERR_TYPE=3)
       INTEGER MPI_ERR_TAG
       PARAMETER (MPI_ERR_TAG=4)
       INTEGER MPI_ERR_COMM
       PARAMETER (MPI_ERR_COMM=5)
       INTEGER MPI_ERR_RANK
       PARAMETER (MPI_ERR_RANK=6)
       INTEGER MPI_ERR_ROOT
       PARAMETER (MPI_ERR_ROOT=7)
       INTEGER MPI_ERR_TRUNCATE
       PARAMETER (MPI_ERR_TRUNCATE=14)
       INTEGER MPI_ERR_GROUP
       PARAMETER (MPI_ERR_GROUP=8)
       INTEGER MPI_ERR_OP
       PARAMETER (MPI_ERR_OP=9)
       INTEGER MPI_ERR_REQUEST
       PARAMETER (MPI_ERR_REQUEST=19)
       INTEGER MPI_ERR_TOPOLOGY
       PARAMETER (MPI_ERR_TOPOLOGY=10)
       INTEGER MPI_ERR_DIMS
       PARAMETER (MPI_ERR_DIMS=11)
       INTEGER MPI_ERR_ARG
       PARAMETER (MPI_ERR_ARG=12)
       INTEGER MPI_ERR_OTHER
       PARAMETER (MPI_ERR_OTHER=15)
       INTEGER MPI_ERR_UNKNOWN
       PARAMETER (MPI_ERR_UNKNOWN=13)
       INTEGER MPI_ERR_INTERN
       PARAMETER (MPI_ERR_INTERN=16)
       INTEGER MPI_ERR_IN_STATUS
       PARAMETER (MPI_ERR_IN_STATUS=17)
       INTEGER MPI_ERR_PENDING
       PARAMETER (MPI_ERR_PENDING=18)
       INTEGER MPI_NOT_IMPLEMENTED
       PARAMETER (MPI_NOT_IMPLEMENTED=49)
       INTEGER MPI_ERR_LASTCODE
       PARAMETER (MPI_ERR_LASTCODE=50)
       INTEGER MPI_ANY_TAG
       PARAMETER (MPI_ANY_TAG=-1)
       INTEGER MPI_ANY_SOURCE
       PARAMETER (MPI_ANY_SOURCE=-1)
       INTEGER MPI_PROC_NULL
       PARAMETER (MPI_PROC_NULL=-2)
       INTEGER MPI_COMM_NULL
       PARAMETER (MPI_COMM_NULL=-1)
       INTEGER MPI_REQUEST_NULL
       PARAMETER (MPI_REQUEST_NULL=-1)
       INTEGER MPI_MAX_PROCESSOR_NAME
       PARAMETER (MPI_MAX_PROCESSOR_NAME=255)
       INTEGER MPI_SOURCE
       PARAMETER (MPI_SOURCE=1)
       INTEGER MPI_TAG
       PARAMETER (MPI_TAG=2)
       INTEGER MPI_ERROR
       PARAMETER (MPI_ERROR=3)
       INTEGER MPI_CART
       PARAMETER (MPI_CART=-2)
       INTEGER MPI_GRAPH
       PARAMETER (MPI_GRAPH=-3)
       INTEGER MPI_TAG_UB
       PARAMETER (MPI_TAG_UB=0)
       INTEGER MPI_HOST
       PARAMETER (MPI_HOST=1)
       INTEGER MPI_IO
       PARAMETER (MPI_IO=2)
       INTEGER MPI_WTIME_IS_GLOBAL
       PARAMETER (MPI_WTIME_IS_GLOBAL=3)
       INTEGER MPI_UNIVERSE_SIZE
       PARAMETER (MPI_UNIVERSE_SIZE=-1)
       INTEGER MPI_LASTUSEDCODE
       PARAMETER (MPI_LASTUSEDCODE=-1)
       INTEGER MPI_APPNUM
       PARAMETER (MPI_APPNUM=-1)
       INTEGER MPI_MAX_ERROR_STRING
       PARAMETER (MPI_MAX_ERROR_STRING=512)
       INTEGER MPI_ERRHANDLER_NULL
       PARAMETER (MPI_ERRHANDLER_NULL=0)
       INTEGER MPI_ERRORS_RETURN
       PARAMETER (MPI_ERRORS_RETURN=1)
       INTEGER MPI_ERRORS_ARE_FATAL
       PARAMETER (MPI_ERRORS_ARE_FATAL=2)
       INTEGER MPI_DATATYPE_NULL
       PARAMETER (MPI_DATATYPE_NULL=-1)
       INTEGER MPI_UB
       PARAMETER (MPI_UB=-2)
       INTEGER MPI_LB
       PARAMETER (MPI_LB=-3)
       INTEGER MPI_CHAR
       PARAMETER (MPI_CHAR=0)
       INTEGER MPI_PACKED
       PARAMETER (MPI_PACKED=13)
       INTEGER MPI_CHARACTER
       PARAMETER (MPI_CHARACTER=0)
       INTEGER MPI_LOGICAL
       PARAMETER (MPI_LOGICAL=22)
       INTEGER MPI_BYTE
       PARAMETER (MPI_BYTE=1)
       INTEGER MPI_SHORT
       PARAMETER (MPI_SHORT=2)
       INTEGER MPI_INT
       PARAMETER (MPI_INT=3)
       INTEGER MPI_INTEGER
       PARAMETER (MPI_INTEGER=3)
       INTEGER MPI_INTEGER1
       PARAMETER (MPI_INTEGER1=24)
       INTEGER MPI_INTEGER2
       PARAMETER (MPI_INTEGER2=25)
       INTEGER MPI_INTEGER4
       PARAMETER (MPI_INTEGER4=26)
       INTEGER MPI_INTEGER8
       PARAMETER (MPI_INTEGER8=27)
       INTEGER MPI_2INT
       PARAMETER (MPI_2INT=18)
       INTEGER MPI_2INTEGER
       PARAMETER (MPI_2INTEGER=18)
       INTEGER MPI_LONG
       PARAMETER (MPI_LONG=4)
       INTEGER MPI_FLOAT
       PARAMETER (MPI_FLOAT=5)
       INTEGER MPI_DOUBLE
       PARAMETER (MPI_DOUBLE=6)
       INTEGER MPI_REAL
       PARAMETER (MPI_REAL=5)
       INTEGER MPI_DOUBLE_PRECISION
       PARAMETER (MPI_DOUBLE_PRECISION=6)
       INTEGER MPI_REAL4
       PARAMETER (MPI_REAL4=28)
       INTEGER MPI_REAL8
       PARAMETER (MPI_REAL8=29)
       INTEGER MPI_REAL16
       PARAMETER (MPI_REAL16=30)
       INTEGER MPI_COMPLEX
       PARAMETER (MPI_COMPLEX=20)
       INTEGER MPI_DOUBLE_COMPLEX
       PARAMETER (MPI_DOUBLE_COMPLEX=23)
       INTEGER MPI_2REAL
       PARAMETER (MPI_2REAL=19)
       INTEGER MPI_2DOUBLE_PRECISION
       PARAMETER (MPI_2DOUBLE_PRECISION=21)
       INTEGER MPI_BOTTOM
       INTEGER MPI_SUM
       PARAMETER (MPI_SUM=0)
       INTEGER MPI_MAX
       PARAMETER (MPI_MAX=1)
       INTEGER MPI_MIN
       PARAMETER (MPI_MIN=2)
       INTEGER MPI_PROD
       PARAMETER (MPI_PROD=3)
       INTEGER MPI_LAND
       PARAMETER (MPI_LAND=4)
       INTEGER MPI_BAND
       PARAMETER (MPI_BAND=5)
       INTEGER MPI_LOR
       PARAMETER (MPI_LOR=6)
       INTEGER MPI_BOR
       PARAMETER (MPI_BOR=7)
       INTEGER MPI_LXOR
       PARAMETER (MPI_LXOR=8)
       INTEGER MPI_BXOR
       PARAMETER (MPI_BXOR=9)
       INTEGER MPI_MINLOC
       PARAMETER (MPI_MINLOC=10)
       INTEGER MPI_MAXLOC
       PARAMETER (MPI_MAXLOC=11)
       INTEGER MPI_STATUS_SIZE
       PARAMETER (MPI_STATUS_SIZE=5)
       INTEGER MPI_REQUEST_SIZE
       PARAMETER (MPI_REQUEST_SIZE=1)
       DOUBLE PRECISION MPI_WTIME, MPI_WTICK
       DOUBLE PRECISION PMPI_WTIME, PMPI_WTICK
