#!/bin/sh
############################# MPC License ############################## 
# Wed Nov 19 15:19:19 CET 2008                                         # 
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
#                                                                      # 
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
# This file is part of the MPC Runtime.                                # 
#                                                                      # 
# This software is governed by the CeCILL-C license under French law   # 
# and abiding by the rules of distribution of free software.  You can  # 
# use, modify and/ or redistribute the software under the terms of     # 
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
# following URL http://www.cecill.info.                                # 
#                                                                      # 
# The fact that you are presently reading this means that you have     # 
# had knowledge of the CeCILL-C license and that you accept its        # 
# terms.                                                               # 
#                                                                      # 
# Authors:                                                             # 
#   - PERACHE Marc marc.perache@cea.fr                                 # 
#                                                                      # 
######################################################################## 
begin_section Generate mpc_status

mkdir -p bin

cat <<EOF > bin/mpc_status
#!/bin/sh
EOF

header_sh >> bin/mpc_status

DATE="`date`"

cat <<EOF >> bin/mpc_status
echo "MPC $MPC_VERSION"
if test "\$1" = "-v"; then 
echo "Build $DATE"
EOF
if test "$CONFIGURE_LINE" != "" ; then
cat <<EOF >> bin/mpc_status
echo "$CONFIGURE_LINE"
EOF
else
cat <<EOF >> bin/mpc_status
echo "$0 $@"
EOF
fi
cat <<EOF >> bin/mpc_status
echo "Module list"
EOF

for i in $MODULE_LIST; do 
cat <<EOF >> bin/mpc_status
echo "    $i"
EOF
done
cat <<EOF >> bin/mpc_status
fi
EOF

chmod 755 bin/mpc_status

end_section
