#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PULVERAIL Sebastien sebastien.pulverail@sogeti.com               #
#                                                                      #
########################################################################

BROWSER="firefox"

print_help(){
cat << EOF
Usage mpc_edit_config [option]

Informations:
    --help,-h Display this help

Browser:
    -b|--browser=<browser_path> to choose a specific browser
EOF
}

# Parse command options
for arg in "$@" ; do
    case $arg in
    -h|--help)
    print_help;
    exit 0;
    ;;
    --browser=*)
    BROWSER="`echo A$arg | sed -e 's/A--browser=//g'`"
    ;;
    -b=*)
    BROWSER="`echo A$arg | sed -e 's/A-b=//g'`"
    ;;
    *)
    echo "Unknow argument $arg.. Exiting!\n"
    print_help;
    exit 0;
    esac
done

export COMMAND="${BROWSER} ${MPC_SHARE_ED_DIR}/index.html"

trap "kill -s 2 0" INT
echo "COMMAND $COMMAND"
$show $COMMAND
rc=$?
#echo $rc

exit $rc

