#!/bin/sh
############################# MPC License ############################## 
# Wed Nov 19 15:19:19 CET 2008                                         # 
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
#                                                                      # 
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
# This file is part of the MPC Runtime.                                # 
#                                                                      # 
# This software is governed by the CeCILL-C license under French law   # 
# and abiding by the rules of distribution of free software.  You can  # 
# use, modify and/ or redistribute the software under the terms of     # 
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
# following URL http://www.cecill.info.                                # 
#                                                                      # 
# The fact that you are presently reading this means that you have     # 
# had knowledge of the CeCILL-C license and that you accept its        # 
# terms.                                                               # 
#                                                                      # 
# Authors:                                                             # 
#   - PERACHE Marc marc.perache@cea.fr                                 # 
#                                                                      # 
######################################################################## 

indent_files(){
    for file in $1/*.c $1/*.h $1/*/*.c $1/*/*.h $1/*/*/*.c $1/*/*/*.h $1/*/*/*/*.c $1/*/*/*/*.h $1/*/*/*/*/*.c $1/*/*/*/*/*.h; do 
	if test -f $file ; then 
	    echo "Indent $file"
	    indent -nbad -bap -nbc -bbo -bl -bli2 -bls -ncdb -nce -cp1 -cs -di2 $file
	    rm $1/*~ $1/*/*~ $1/*/*/*~ > /dev/null 2>&1
	fi
    done
}

LIST=""
for i in MPC_*; do
if test "$i" != "MPC_Extras" ; then 
LIST="$LIST $i"
fi
done

if test " $@" != " " ; then 
LIST="$@"
fi 


for i in $LIST; do
for j in $i/* ; do 
    if test -d $j ; then 
	indent_files $j
    fi 
done
done
