#!/bin/sh
############################# MPC License ############################## 
# Wed Nov 19 15:19:19 CET 2008                                         # 
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
#                                                                      # 
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
# This file is part of the MPC Runtime.                                # 
#                                                                      # 
# This software is governed by the CeCILL-C license under French law   # 
# and abiding by the rules of distribution of free software.  You can  # 
# use, modify and/ or redistribute the software under the terms of     # 
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
# following URL http://www.cecill.info.                                # 
#                                                                      # 
# The fact that you are presently reading this means that you have     # 
# had knowledge of the CeCILL-C license and that you accept its        # 
# terms.                                                               # 
#                                                                      # 
# Authors:                                                             # 
#   - PERACHE Marc marc.perache@cea.fr                                 # 
#                                                                      # 
######################################################################## 

WARN="0"
NIMP="0"

for i in MPC_*; do 
echo $i
(cd $i ;grep -nri not_implemented * | grep -v ".svn" | grep -v "~")
(cd $i ;grep -nri "#warning" * | grep -v ".svn" | grep -v "~")

LNIMP="`(cd $i ;grep -nri not_implemented * | grep -v \".svn\" | grep -v \"~\")| wc -l`"
LWARN="`(cd $i ;grep -nri \"#warning\" * | grep -v \".svn\" | grep -v \"~\")| wc -l`"
#echo 
echo "$LNIMP not implemented functions $LWARN warnings"
echo 

WARN="`expr $WARN + $LWARN`"
NIMP="`expr $NIMP + $LNIMP`"

done
echo
echo "$NIMP not implemented functions $WARN warnings"