#!/bin/sh

USER=`whoami`
FILE=$1

usage(){
    echo "Usage $0 patch_file"
}

if test "$FILE" =  "" ; then  
usage
exit 1
fi

curl --negotiate -u $USER -k https://jenkins.ccc.ocre.cea.fr/mpc_nr/job/MPC_Add_hotfix/build -F file0=@$FILE -F json='{"parameter": [{"name":"./patch_file", "file":"file0"}]}'
