#!/bin/sh

check_ret(){
    $@
    if test "$?" != "0" ; then 
	echo "Fatal Error "
	exit 1
    fi
}


GIT_BRANCH_ORIG="`git rev-parse --abbrev-ref HEAD`"
GIT_BRANCH_CUR="`git rev-parse --abbrev-ref HEAD`"

DONE="n"
while test "$DONE" != "y"; do
echo "Using branch $GIT_BRANCH_CUR [y/n]"
read DONE

if test "$GIT_BRANCH_CUR" = "devel"; then
DONE="n"
fi

if test "$DONE" != "y"; then  
echo "Enter a new branch name"
read GIT_BRANCH_CUR
fi
done

GIT_BRANCH_NEW="merge_to_devel_${GIT_BRANCH_CUR}"

check_ret git checkout -b ${GIT_BRANCH_NEW}

check_ret git push -u origin ${GIT_BRANCH_NEW}

echo "New branch for merge ${GIT_BRANCH_NEW}"
check_ret git checkout ${GIT_BRANCH_ORIG}


