#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#                                                                      #
########################################################################

generate(){
    name="$1"
    NAME="$1"
    NAME="`echo $NAME | sed s,a,A,g`"
    NAME="`echo $NAME | sed s,b,B,g`"
    NAME="`echo $NAME | sed s,c,C,g`"
    NAME="`echo $NAME | sed s,d,D,g`"
    NAME="`echo $NAME | sed s,e,E,g`"
    NAME="`echo $NAME | sed s,f,F,g`"
    NAME="`echo $NAME | sed s,g,G,g`"
    NAME="`echo $NAME | sed s,h,H,g`"
    NAME="`echo $NAME | sed s,i,I,g`"
    NAME="`echo $NAME | sed s,j,J,g`"
    NAME="`echo $NAME | sed s,k,K,g`"
    NAME="`echo $NAME | sed s,l,L,g`"
    NAME="`echo $NAME | sed s,m,M,g`"
    NAME="`echo $NAME | sed s,n,N,g`"
    NAME="`echo $NAME | sed s,o,O,g`"
    NAME="`echo $NAME | sed s,p,P,g`"
    NAME="`echo $NAME | sed s,q,Q,g`"
    NAME="`echo $NAME | sed s,r,R,g`"
    NAME="`echo $NAME | sed s,s,S,g`"
    NAME="`echo $NAME | sed s,t,T,g`"
    NAME="`echo $NAME | sed s,u,U,g`"
    NAME="`echo $NAME | sed s,v,V,g`"
    NAME="`echo $NAME | sed s,w,W,g`"
    NAME="`echo $NAME | sed s,x,X,g`"
    NAME="`echo $NAME | sed s,y,Y,g`"
    NAME="`echo $NAME | sed s,z,Z,g`"

    if test -f sctk_${name}.h; then 
	echo "File sctk_${name}.h exist"
	exit 1
    fi
    if test -f sctk_${name}.c; then 
	echo "File sctk_${name}.c exist"
	exit 1
    fi

    echo "Generate $name/$NAME"
    cat sctk_none.h | sed s,none,$name,g | sed s,NONE,$NAME,g > sctk_${name}.h
    cat sctk_none.c | sed s,none,$name,g | sed s,NONE,$NAME,g > sctk_${name}.c
}

for arg in $@; do
    if test "$arg" != "none" ; then 
	generate $arg
    fi
done