#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - Sebastien Valat sebastien.valat@cea.fr                           #
#                                                                      #
########################################################################

##################### FUNCTION ###################
safe_exec()
{
	echo "$*"
	$* || exit 1
}
##################### FUNCTION ###################
do_check()
{
	if test -d MPC_${VERSION}; then safe_exec rm -rf MPC_${VERSION}; fi
	safe_exec tar -xzf MPC_${VERSION}.tar.gz
	safe_exec cp -r ./MPC_Test_Suite ./MPC_${VERSION}/
	safe_exec cd MPC_${VERSION}/MPC_Test_Suite
	./mpc_validation --build --submit
	safe_exec ./mpc_validation --test --submit --fast
}

##################### SECTION ####################
if test ! -f mpcframework/.MPC_version && test ! -d tools && test ! -d mpcframework; then
	echo "Please run this script from the root directory of MPC" 1>&2
	exit 1
fi

##################### SECTION ####################
if test ! -e .git; then
	echo "This script is made to generate an archive from a Git repository !" 1>&2
	exit 1
fi

##################### SECTION ####################
VERSION=$(cd ./mpcframework && ./MPC_Tools/mpc_print_version)
echo "MPC version for this archive will be $VERSION"
test -f ./mpcframework-${VERSION}.tar.gz && echo "A file named mpcframework-${VERSION}.tar.gz already exist!" && exit 1

git describe --exact-match MPC_${VERSION} > /dev/null 2>&1 || echo "If this is a release archive, please create an annotated tag for the following hash: `git rev-parse HEAD`"

echo "git archive --format=tar.gz --prefix=mpcframework-${VERSION}/ HEAD > mpcframework-${VERSION}.tar.gz"
git archive --format=tar.gz --prefix=mpcframework-${VERSION}/ HEAD > mpcframework-${VERSION}.tar.gz || exit 1

echo "Archive SHA256 sum: `command -v sha256sum > /dev/null 2>&1 && sha256sum mpcframework-${VERSION}.tar.gz`"

if test "$1" = "--check"; then
	do_check
fi

echo "Done."
