#!/bin/bash
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - CARRIBAULT Patrick patrick.carribault@cea.fr                     #
#   - PERACHE Marc marc.perache@cea.fr                                 #
#   - JAEGER Julien julien.jaeger@cea.fr                               #
#                                                                      #
########################################################################

UTILS_DIR="$(dirname "`readlink -f $0`")"

MAJOR_VERSION=
MINOR_VERSION=
PATCH_VERSION=
TAINT_VERSION=

if test -n "$(command -v git)" -a -e "$UTILS_DIR/../.git"; then
	res=$(git -C $UTILS_DIR describe --abbrev=0 2>/dev/null | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+$")
	MAJOR_VERSION=$(echo "$res" | cut -f1 -d".")
	MINOR_VERSION=$(echo "$res" | cut -f2 -d".")
	PATCH_VERSION=$(echo "$res" | cut -f3 -d".")
	TAINT_VERSION="@$(git -C $UTILS_DIR rev-parse --short HEAD)"
	git -C $UTILS_DIR diff --quiet || TAINT_VERSION="$TAINT_VERSION-dirty"
fi

#two scenarios: no Git repo OR issues with fetching tags
# -> rollback
if test -z "$MAJOR_VERSION"; then
	. $UTILS_DIR/../VERSION
	MAJOR_VERSION=$major
	MINOR_VERSION=$minor
	PATCH_VERSION=$patch
	TAINT_VERSION=""
fi

for i in $@; do
	case $i in
		--major)
			echo "$MAJOR_VERSION"
			;;
		--minor)
			echo "$MINOR_VERSION"
			;;
		--patch)
			echo "$PATCH_VERSION"
			;;
		--taint)
			echo "$TAINT_VERSION"
			;;
		--all)
			echo "$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION$TAINT_VERSION"
			;;
		*)
			;;
	esac
done

if test $# = "0"; then
	printf "$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
fi
