#!/bin/bash
error()
{
	printf "ERROR: $@\n"
	exit 42
}


which pandoc >/dev/null 2>&1 || error "Failed to find 'pandoc' to build static man-pages"
test -f ./build_manpage || error "Run this script from MPC_Doc directory only"

regex="man/man([[:digit:]])/(.*)\.md"
if test -z "$1"; then
for markdown in `find man/ -name "*.md"`
do
	if [[ $markdown =~ $regex ]]; then
		mannum="${BASH_REMATCH[1]}"
		manname="${BASH_REMATCH[2]}"
		manfile="./man_static/man${mannum}/${manname}.${mannum}in"
		echo "Updating $markdown -> $manfile"
		pandoc -s $markdown -t man > $manfile
	fi
done
else
	pandoc -s "$1" -t man
fi
