#!/bin/sh

. ../.MPC_version || exit 24

file="$1"
version="$MAJOR.$MINOR.$REVISION"
test -n "$PRE_RELEASE" && version="$version$PRE_RELEASE"
test -n "$file" || exit 42

sed -e "s@#PACKAGE_DATE#@`date +%x`@" \
    -e "s@#PACKAGE_VERSION#@$version@" \
    -e "s@#PACKAGE_NAME#@Multi-Processor Computing@" $file


if test -n "`echo "$file" | grep "MPI_.*.3in"`"; then
cat<<EOF
.SH DISCLAIMER
.ft R
This man page, while documenting a function from the MPI standard, is fully part of the OpenMPI implementation and the "Multi-Processor Computing" (MPC) team complies in full respect regarding the MPI standard. It has been generated and original authors are mentioned in the Open-MPI project.

The Open-MPI project is distributed under the 3-clause BSD license and freely available at https://www.open-mpi.org/. There is NO WARRANTY to the extent permitted by law.

.SH REPORTING BUGS
.ft R
Julien Jaeger <julien.jaeger@cea.fr>, ParaTools Staff <info@paratools.com>

EOF
fi
