#!/bin/sh

. ../.MPC_version || exit 24

test -n "$1" || exit 42
manpage="`cat $1`"
version="$MAJOR.$MINOR.$REVISION"
test -n "$PRE_RELEASE" && version="$version$PRE_RELEASE"

# Check if we can have an updated version of the man-page...
# 1. Check if the Markdown file exist for this man-page
original="`echo "$file" | sed -e "s,^man_static/,man/," -e "s,\.[0-9]in,\.md,"`"
# 2. if so, build the man-page from the Markdown
test -f "$original" && updated="`./build_manpage $original`"
# 3. If succeeded, use the output
test -n "$updated" && manpage="$updated"

echo "$manpage" | sed -e "s@#PACKAGE_DATE#@`date +%x`@" \
    -e "s@#PACKAGE_VERSION#@$version@" \
    -e "s@#PACKAGE_NAME#@Multi-Processor Computing@"


if test -n "`echo "$file" | grep "MPI_.*.3in"`"; then
cat<<EOF
.SH DISCLAIMER
.ft R
This man page, while documenting a function from the MPI standard, is fully part of the OpenMPI implementation and the "Multi-Processor Computing" (MPC) team complies in full respect regarding the MPI standard. It has been generated and original authors are mentioned in the Open-MPI project.

The Open-MPI project is distributed under the 3-clause BSD license and freely available at https://www.open-mpi.org/. There is NO WARRANTY to the extent permitted by law.

EOF
fi

cat<<EOF
.SH REPORTING BUGS
.ft R
Julien Jaeger <julien.jaeger@cea.fr>, ParaTools Staff <info@paratools.com>
EOF
