#!/bin/sh
############################# MPC License ##############################
# Wed May 21 15:46:19 CET 2014                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - VET Jean-Yves vet.jean.yves@gmail.com                            #
#                                                                      #
########################################################################

. ../.MPC_version

# Update variables
MPC_VERSION="${MAJOR}.${MINOR}.${REVISION}"
OMP_VERSION="2.5"
MPI_VERSION="1.3"

# Replace variables
cat ${1}.template \
	| sed -e "s/@MPC_VERSION@/${MPC_VERSION}/g" \
	| sed -e "s/@OMP_VERSION@/${OMP_VERSION}/g" \
	| sed -e "s/@MPI_VERSION@/${MPI_VERSION}/g" \
	> ${1}

gimli -f ${1}
