#!/bin/sh
############################# MPC License ############################## 
# Wed Nov 19 15:19:19 CET 2008                                         # 
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # 
#                                                                      # 
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            # 
# This file is part of the MPC Runtime.                                # 
#                                                                      # 
# This software is governed by the CeCILL-C license under French law   # 
# and abiding by the rules of distribution of free software.  You can  # 
# use, modify and/ or redistribute the software under the terms of     # 
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # 
# following URL http://www.cecill.info.                                # 
#                                                                      # 
# The fact that you are presently reading this means that you have     # 
# had knowledge of the CeCILL-C license and that you accept its        # 
# terms.                                                               # 
#                                                                      # 
# Authors:                                                             # 
#   - PERACHE Marc marc.perache@cea.fr                                 # 
#                                                                      # 
######################################################################## 
#echo "$LAUNCH_COMMAND"

if [ "$SCTK_JOB_MANAGER" = "SLURM" ]; then
    if test "$CPU_NB" = "0" ; then
                if test "$SLURM_CPUS_PER_TASK" != "" ; then
                    CPU_NB="$SLURM_CPUS_PER_TASK"
                else
                    CPU_NB=1
                fi
    fi

	LAUNCH_COMMAND="srun $LAUNCH_OPTIONS --ntasks=$PROCESS_NB --nodes=$NODE_NB --cpus-per-task=$CPU_NB /bin/env DISPLAY=$DISPLAY xterm -e $DEBUG $MPC_GDB_DEBUG_ARGS --args $BINARY -$USER_ARGS $SCTK_ARGS"
else
	echo  "ERROR mpc is compiled without slurm support" 1>&2
	exit 1
fi
