#!/bin/bash

arch="`uname -m`"
dir="`dirname $0`"
cmd="`basename $0`"

case "$arch" in
	x86_64)
		subprefix=x86_64
		;;
	mic|k1om)
		subprefix=k1om
		;;
	*)
		echo "Unsupported architecture, or auto-detection error : $arch" 1>&2
		exit 1
		;;
esac

"$dir/../../${subprefix}/mpcframework/bin/${cmd}" "$@"
exit $?
