#!/bin/sh
############################# MPC License ##############################
# Wed Nov 19 15:19:19 CET 2008                                         #
# Copyright or (C) or Copr. Commissariat a l'Energie Atomique          #
#                                                                      #
# IDDN.FR.001.230040.000.S.P.2007.000.10000                            #
# This file is part of the MPC Runtime.                                #
#                                                                      #
# This software is governed by the CeCILL-C license under French law   #
# and abiding by the rules of distribution of free software.  You can  #
# use, modify and/ or redistribute the software under the terms of     #
# the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     #
# following URL http://www.cecill.info.                                #
#                                                                      #
# The fact that you are presently reading this means that you have     #
# had knowledge of the CeCILL-C license and that you accept its        #
# terms.                                                               #
#                                                                      #
# Authors:                                                             #
#   - Sebastien Valat sebastien.valat@cea.fr                           #
#                                                                      #
########################################################################

##################### FUNCTION ###################
safe_exec()
{
	echo "$*"
	$* || exit 1
}
##################### FUNCTION ###################
do_check()
{
	if test -d MPC_${VERSION}; then safe_exec rm -rf MPC_${VERSION}; fi
	safe_exec tar -xzf MPC_${VERSION}.tar.gz
	safe_exec cp -r ./MPC_Test_Suite ./MPC_${VERSION}/
	safe_exec cd MPC_${VERSION}/MPC_Test_Suite
	./mpc_validation --build --submit
	safe_exec ./mpc_validation --test --submit --fast
}

##################### SECTION ####################
if test ! -f mpcframework/.MPC_version && test ! -d tools && test ! -d mpcframework; then
	echo "Please run this script from the root directory of MPC" 1>&2
	exit 1
fi

##################### SECTION ####################
if test ! -f .git && test ! -f .gitattributes; then
	echo "This script only work on a git working copy" 1>&2
	exit 1
fi

##################### SECTION ####################
VERSION=$(cd ./mpcframework && ./MPC_Tools/mpc_print_version)
echo "MPC version is $VERSION"

echo "Generate archive..."
echo "git archive --format=tar --prefix=MPC_${VERSION}/ HEAD | gzip > MPC_${VERSION}.tar.gz"
git archive --format=tar --prefix=MPC_${VERSION}/ HEAD | gzip > MPC_${VERSION}.tar.gz || exit 1

cp MPC_${VERSION}.tar.gz MPC_light_${VERSION}.tar.gz 

gunzip MPC_light_${VERSION}.tar.gz

REMOVE_LIST=""
REMOVE_LIST_SIZE=""
for j in binutils  gcc  gdb  gmp  hwloc  hydra  libxml2  mpc mpfr; do 
for i in extern-deps/$j/*.tar.*; do 
	echo "Exclude $i"
	REMOVE_LIST="$REMOVE_LIST MPC_${VERSION}/$i"
	REMOVE_LIST_SIZE="$REMOVE_LIST_SIZE $i"
done
done

echo "Remove"
du -csh $REMOVE_LIST_SIZE

tar -vf MPC_light_${VERSION}.tar --delete $REMOVE_LIST
gzip MPC_light_${VERSION}.tar 

md5sum MPC_${VERSION}.tar.gz MPC_light_${VERSION}.tar.gz 


if test "$1" = "--check"; then
	do_check
fi

echo "Done."
