/* ############################# MPC License ############################## */
/* # Wed Nov 19 15:19:19 CET 2008                                         # */
/* # Copyright or (C) or Copr. Commissariat a l'Energie Atomique          # */
/* #                                                                      # */
/* # IDDN.FR.001.230040.000.S.P.2007.000.10000                            # */
/* # This file is part of the MPC Runtime.                                # */
/* #                                                                      # */
/* # This software is governed by the CeCILL-C license under French law   # */
/* # and abiding by the rules of distribution of free software.  You can  # */
/* # use, modify and/ or redistribute the software under the terms of     # */
/* # the CeCILL-C license as circulated by CEA, CNRS and INRIA at the     # */
/* # following URL http://www.cecill.info.                                # */
/* #                                                                      # */
/* # The fact that you are presently reading this means that you have     # */
/* # had knowledge of the CeCILL-C license and that you accept its        # */
/* # terms.                                                               # */
/* #                                                                      # */
/* # Authors:                                                             # */
/* #   - BESNARD Jean-Baptiste jean-baptiste.besnard@cea.fr               # */
/* #                                                                      # */
/* ######################################################################## */

/* Syntax : PROBE( UNIQUE_KEY, PARENT_KEY, "Short Desc")
 * use NO_PARENT if a given probe has no paren */

PROBE( MPI, NO_PARENT, MPI Interface)
	PROBE( MPI_POINT_TO_POINT, MPI, MPI point to point)
		PROBE( MPC_Iprobe, MPI_POINT_TO_POINT , MPC_Iprobe)
		PROBE( MPC_Probe, MPI_POINT_TO_POINT , MPC_Probe)
		PROBE( MPC_Irecv, MPI_POINT_TO_POINT,  MPC_Irecv)
		PROBE( MPC_Irecv_pack, MPI_POINT_TO_POINT,  MPC_Irecv_pack)
		PROBE( MPC_Irsend, MPI_POINT_TO_POINT,  MPC_Irsend)
		PROBE( MPC_Isend, MPI_POINT_TO_POINT,  MPC_Isend)
		PROBE( MPC_Isend_pack, MPI_POINT_TO_POINT,  MPC_Isend_pack)
		PROBE( MPC_Issend, MPI_POINT_TO_POINT,  MPC_Issend)
		PROBE( MPC_Recv, MPI_POINT_TO_POINT,  MPC_Recv)
		PROBE( MPC_Rsend, MPI_POINT_TO_POINT,  MPC_Rsend)
		PROBE( MPC_Send, MPI_POINT_TO_POINT,  MPC_Send)
		PROBE( MPC_Sendrecv, MPI_POINT_TO_POINT,  MPC_Sendrecv)
		PROBE( MPC_Ssend, MPI_POINT_TO_POINT,  MPC_Ssend)
		PROBE( MPC_Ibsend, MPI_POINT_TO_POINT,  MPC_Ibsend)
		PROBE( MPC_Test, MPI_POINT_TO_POINT,  MPC_Test)
		PROBE( MPC_Test_no_check, MPI_POINT_TO_POINT,  MPC_Test_no_check)
		PROBE( MPC_Test_check, MPI_POINT_TO_POINT,  MPC_Test_check)
		PROBE( MPC_Proceed, MPI_POINT_TO_POINT,  MPC_Proceed)
	PROBE( MPI_WAIT, MPI, MPI Waiting)
		PROBE( MPC_Wait, MPI_WAIT,  MPC_Wait)
		PROBE( MPC_Wait_pending, MPI_WAIT,  MPC_Wait_pending)
		PROBE( MPC_Wait_pending_all_comm, MPI_WAIT,  MPC_Wait_pending_all_comm)
		PROBE( MPC_Waitall, MPI_WAIT,  MPC_Waitall)
		PROBE( MPC_Waitany, MPI_WAIT,  MPC_Waitany)
		PROBE( MPC_Waitsome, MPI_WAIT,  MPC_Waitsome)
	PROBE( MPI_COLL, MPI, MPI collectives)
		PROBE( MPC_Allgather, MPI_COLL,  MPC_Allgather)
		PROBE( MPC_Allgatherv, MPI_COLL,  MPC_Allgatherv)
		PROBE( MPC_Allreduce, MPI_COLL,  MPC_Allreduce)
		PROBE( MPC_Alltoall, MPI_COLL,  MPC_Alltoall)
		PROBE( MPC_Alltoallv, MPI_COLL,  MPC_Alltoallv)
		PROBE( MPC_Barrier, MPI_COLL,  MPC_Barrier)
		PROBE( MPC_Bcast, MPI_COLL,  MPC_Bcast)
		PROBE( MPC_Bsend, MPI_COLL,  MPC_Bsend)
		PROBE( MPC_Gather, MPI_COLL,  MPC_Gather)
		PROBE( MPC_Gatherv, MPI_COLL,  MPC_Gatherv)
		PROBE( MPC_Reduce, MPI_COLL,  MPC_Reduce)
		PROBE( MPC_Scatter, MPI_COLL,  MPC_Scatter)
		PROBE( MPC_Scatterv, MPI_COLL,  MPC_Scatterv)
	PROBE( MPI_COMMUNICATORS, MPI, MPI Communicator)
		PROBE( MPC_Comm_create, MPI_COMMUNICATORS,  MPC_Comm_create)
		PROBE( MPC_Comm_create_list, MPI_COMMUNICATORS,  MPC_Comm_create_list)
		PROBE( MPC_Comm_dup, MPI_COMMUNICATORS,  MPC_Comm_dup)
		PROBE( MPC_Comm_free, MPI_COMMUNICATORS,  MPC_Comm_free)
		PROBE( MPC_Comm_split, MPI_COMMUNICATORS,  MPC_Comm_split)
	PROBE( MPI_GROUPS, MPI, MPI Group)
		PROBE( MPC_Comm_group, MPI_GROUPS,  MPC_Comm_group)
		PROBE( MPC_Group_difference, MPI_GROUPS,  MPC_Group_difference)
		PROBE( MPC_Group_free, MPI_GROUPS,  MPC_Group_free)
		PROBE( MPC_Group_incl, MPI_GROUPS,  MPC_Group_incl)
	PROBE( MPI_PACK, MPI, MPI Group)
		PROBE( MPC_Add_pack, MPI_PACK,  MPC_Add_pack)
		PROBE( MPC_Add_pack_absolute, MPI_PACK,  MPC_Add_pack_absolute)
		PROBE( MPC_Add_pack_default, MPI_PACK,  MPC_Add_pack_default)
		PROBE( MPC_Default_pack, MPI_PACK,  MPC_Default_pack)
		PROBE( MPC_Open_pack, MPI_PACK,  MPC_Open_pack)
	PROBE( MPI_RANK, MPI, MPI rank and context)
		PROBE( MPC_Node_number, MPI_RANK,  MPC_Node_number)
		PROBE( MPC_Node_rank, MPI_RANK,  MPC_Node_rank)
		PROBE( MPC_Process_number, MPI_RANK,  MPC_Process_number)
		PROBE( MPC_Process_rank, MPI_RANK,  MPC_Process_rank)
		PROBE( MPC_Processor_number, MPI_RANK,  MPC_Processor_number)
		PROBE( MPC_Processor_rank, MPI_RANK,  MPC_Processor_rank)
		PROBE( MPC_Comm_rank, MPI_RANK,  MPC_Comm_rank)
		PROBE( MPC_Comm_size, MPI_RANK,  MPC_Comm_size)
		PROBE( MPC_Get_processor_name, MPI_RANK,  MPC_Get_processor_name)
		PROBE( MPC_Get_count, MPI_RANK,  MPC_Get_count)
		PROBE( MPC_Wtime, MPI_RANK , MPC_Wtime)
		PROBE( MPC_Local_process_rank, MPI_RANK, MPC_Local_process_rank)
		PROBE( MPC_Local_process_number, MPI_RANK, MPC_Local_process_number)
		PROBE( MPC_Task_rank, MPI_RANK, MPC_Task_rank)
		PROBE( MPC_Task_number, MPI_RANK, MPC_Task_number)
	PROBE( MPI_ERROR, MPI, MPI error related)
		PROBE( MPC_Errhandler_create, MPI_ERROR,  MPC_Errhandler_create)
		PROBE( MPC_Errhandler_free, MPI_ERROR,  MPC_Errhandler_free)
		PROBE( MPC_Errhandler_get, MPI_ERROR,  MPC_Errhandler_get)
		PROBE( MPC_Errhandler_set, MPI_ERROR,  MPC_Errhandler_set)
		PROBE( MPC_Error_class, MPI_ERROR,  MPC_Error_class)
		PROBE( MPC_Error_string, MPI_ERROR,  MPC_Error_string)
		PROBE( MPC_Abort, MPI_ERROR,  MPC_Abort)
	PROBE( MPI_TYPES, MPI, MPI types related)
		PROBE( MPC_Sizeof_datatype, MPI_TYPES,  MPC_Sizeof_datatype)
		PROBE( MPC_Type_free, MPI_TYPES,  MPC_Type_free)
		PROBE( MPC_Type_size, MPI_TYPES,  MPC_Type_size)
		PROBE( MPC_Derived_datatype, MPI_TYPES,  MPC_Derived_datatype)
	PROBE( MPI_OP, MPI, MPI Operation related)
		PROBE( MPC_Op_create, MPI_OP , MPC_Op_create)
		PROBE( MPC_Op_free, MPI_OP , MPC_Op_free)
	PROBE( MPI_SETUP, MPI, MPI Init and release)
		PROBE( MPC_Finalize, MPI_SETUP , MPC_Finalize)
		PROBE( MPC_Init, MPI_SETUP , MPC_Init)
		PROBE( MPC_Initialized, MPI_SETUP , MPC_Initialized)
	PROBE( MPI_INTERNAL, MPI, Internals)
                PROBE (MPC_Copy_message,MPI_INTERNAL,MPC_Copy_message)
                PROBE (MPC_Test_message_search_matching,MPI_INTERNAL,MPC_Test_message_search_matching)
                PROBE (MPC_Test_message_pair_locked,MPI_INTERNAL,MPC_Test_message_pair_locked)
                PROBE (MPC_Test_message_pair,MPI_INTERNAL,MPC_Test_message_pair)
                PROBE (MPC_Test_message_pair_try,MPI_INTERNAL,MPC_Test_message_pair_try)
                PROBE (MPC_Test_message_pair_try_lock,MPI_INTERNAL,MPC_Test_message_pair_try_lock)




PROBE( ALLOCATOR, NO_PARENT, MPC Allocator)
	PROBE( POSIX_ALLOC, ALLOCATOR, Posix allocator Interface)
		SIZE_COUNTER( malloc_size, POSIX_ALLOC, size allocated by  malloc)
		PROBE( malloc, POSIX_ALLOC,  malloc)
		PROBE( calloc, POSIX_ALLOC,  calloc)
		PROBE( realloc, POSIX_ALLOC,  realloc)
		PROBE( free, POSIX_ALLOC,  free)
		PROBE( memalign, POSIX_ALLOC, memalign)
		PROBE( posix_memalign, POSIX_ALLOC, posix_memalign)
	PROBE( MPC_ALLOC, ALLOCATOR, MPC internal allocator Interface)
		PROBE( sctk_malloc, MPC_ALLOC,  sctk_malloc)
		SIZE_COUNTER( sctk_malloc_size, MPC_ALLOC, size allocated by sctk_malloc)
		PROBE( sctk_calloc, MPC_ALLOC,  sctk_calloc)
		PROBE( sctk_memalign, MPC_ALLOC,  sctk_memalign)
		PROBE( sctk_posix_memalign, MPC_ALLOC,  sctk_posix_memalign)
		PROBE( sctk_realloc_inter_chain, MPC_ALLOC,  sctk_realloc_inter_chain)
		PROBE( sctk_alloc_posix_numa_migrate, MPC_ALLOC, sctk_alloc_posix_numa_migrate)
		PROBE( sctk_alloc_posix_setup_tls_chain, MPC_ALLOC, sctk_alloc_posix_setup_tls_chain)
		PROBE( sctk_realloc, MPC_ALLOC,  sctk_realloc)
		PROBE( sctk_free, MPC_ALLOC,  sctk_free)
		PROBE( sctk_sbrk, MPC_ALLOC,  sctk_sbrk)
		PROBE( sctk_sbrk_try_to_find_page, MPC_ALLOC,  sctk_sbrk_try_to_find_page)
		PROBE( sctk_sbrk_mmap, MPC_ALLOC,  sctk_sbrk_mmap)
		PROBE( sctk_free_distant, MPC_ALLOC,  sctk_free_distant)
		PROBE( sctk_mmap, MPC_ALLOC,  sctk_mmap)
		PROBE( sctk_alloc_ptr_small_serach_chunk, MPC_ALLOC,  sctk_alloc_ptr_small_serach_chunk)
		PROBE( sctk_alloc_ptr_big, MPC_ALLOC,  sctk_alloc_ptr_big)
		PROBE( sctk_alloc_ptr_small, MPC_ALLOC,  sctk_alloc_ptr_small)
		PROBE( sctk_free_small, MPC_ALLOC,  sctk_free_small)
		PROBE( sctk_free_big, MPC_ALLOC,  sctk_free_big)

PROBE( THREAD, NO_PARENT, MPI Thread)
	PROBE( sctk_thread_mutex_lock, THREAD,  sctk_thread_mutex_lock)
	PROBE( sctk_thread_mutex_unlock, THREAD,  sctk_thread_mutex_unlock)
	PROBE( sctk_thread_mutex_spinlock, THREAD,  sctk_thread_mutex_spinlock)
	PROBE( sctk_thread_wait_for_value_and_poll, THREAD,  sctk_thread_wait_for_value_and_poll)
	PROBE( sctk_thread_wait_for_value, THREAD,  sctk_thread_wait_for_value)

PROBE( MESSAGE_PASSING_INT, NO_PARENT, MPC Message passing internals )
	PROBE( sctk_elan_barrier, MESSAGE_PASSING_INT,  sctk_elan_barrier)
	PROBE( sctk_net_send_ptp_message_driver, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver)
	PROBE( sctk_net_get_new_header, MESSAGE_PASSING_INT,  sctk_net_get_new_header)
	PROBE( sctk_net_send_ptp_message_driver_inf, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_inf)
	PROBE( sctk_net_send_ptp_message_driver_sup, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_sup)
	PROBE( sctk_net_send_ptp_message_driver_sup_write, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_sup_write)
	PROBE( sctk_net_send_ptp_message_driver_split_header, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_split_header)
	PROBE( sctk_net_send_ptp_message_driver_send_header, MESSAGE_PASSING_INT,  sctk_net_send_ptp_message_driver_send_header)


PROBE( OPEN_MP, NO_PARENT, MPC Message passing internals )
	PROBE( __sctk_microthread_parallel_exec__last_barrier , OPEN_MP,  __sctk_microthread_parallel_exec__last_barrier)
	PROBE( __mpcomp_start_parallel_region, OPEN_MP,  __mpcomp_start_parallel_region)
	PROBE( __mpcomp_start_parallel_region__creation, OPEN_MP,  __mpcomp_start_parallel_region__creation)
